unpackaged/main/default/objects/Lot__c/Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lot__c/fields/Base_Model_Price_Override__c.field-meta.xml
<CustomField>
        <fullName>Base_Model_Price_Override__c</fullName>
        <label>Base Model Price Override</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Preconfigured_Options_Amount__c.field-meta.xml
<CustomField>
        <fullName>Preconfigured_Options_Amount__c</fullName>
        <label>Preconfigured Options Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Premium__c.field-meta.xml
<CustomField>
        <fullName>Premium__c</fullName>
        <label>Premium</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Price__c.field-meta.xml
<CustomField>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Marketing_Community__c/Marketing_Community__c.object-meta.xml
<CustomObject>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Marketing_Community__c/fields/Sales_Process_Type__c.field-meta.xml
<CustomField>
        <fullName>Sales_Process_Type__c</fullName>
        <defaultValue>'Direct offer'</defaultValue>
        <label>Default Sales Process Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct offer</fullName>
                </value>
                <value>
                    <fullName>Lot reservation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Model__c/fields/Price__c.field-meta.xml
<CustomField>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Model__c/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Models</relationshipLabel>
        <relationshipName>Models</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Base_Model_Price__c.field-meta.xml
<CustomField>
        <fullName>Base_Model_Price__c</fullName>
        <label>Base Model Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lot__c.field-meta.xml
<CustomField>
        <fullName>Lot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Lot</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Lot must belong to the selected subdivision, be available (open) and be released for sale.</errorMessage>
            <filterItems>
                <field>Lot__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <filterItems>
                <field>Lot__c.Released_for_Sale__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Lot__c.Status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Lot__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lot_Premium__c.field-meta.xml
<CustomField>
        <fullName>Lot_Premium__c</fullName>
        <label>Lot Premium</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lot_Price__c.field-meta.xml
<CustomField>
        <fullName>Lot_Price__c</fullName>
        <label>Lot Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Model__c.field-meta.xml
<CustomField>
        <fullName>Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Model must belong to the selected subdivision.</errorMessage>
            <filterItems>
                <field>Model__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Model__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Scenario_Name__c.field-meta.xml
<CustomField>
        <fullName>Scenario_Name__c</fullName>
        <label>Scenario Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Subdivision must belong to the selected sales office and the selected marketing community.</errorMessage>
            <filterItems>
                <field>Subdivision__c.Sales_Office__c</field>
                <operation>equals</operation>
                <valueField>$Source.Sales_Office__c</valueField>
            </filterItems>
            <filterItems>
                <field>Subdivision__c.Marketing_Community__c</field>
                <operation>equals</operation>
                <valueField>$Source.Marketing_Community__c</valueField>
            </filterItems>
            <infoMessage>Select a subdivision</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Actual_Sale_Amount__c.field-meta.xml
<CustomField>
        <fullName>Total_Actual_Sale_Amount__c</fullName>
        <label>Total Actual Sale Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Discount_Amount__c.field-meta.xml
<CustomField>
        <fullName>Total_Discount_Amount__c</fullName>
        <label>Total Discount Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Options_Amount__c.field-meta.xml
<CustomField>
        <fullName>Total_Options_Amount__c</fullName>
        <label>Total Options Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Tax_Amount__c.field-meta.xml
<CustomField>
        <fullName>Total_Tax_Amount__c</fullName>
        <label>Total Tax Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Tax_Rebate_Amount__c.field-meta.xml
<CustomField>
        <fullName>Total_Tax_Rebate_Amount__c</fullName>
        <label>Total Tax Rebate Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/Subdivision__c.object-meta.xml
<CustomObject>
    <description>NEWSTAR Sales Subdivision</description>
    <label>Subdivision</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subdivisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subdivision__c/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/NewstarOpporunityInfoService.cls
public with sharing class NewstarOpporunityInfoService {

    public static void setOpportunityNameAtMarketingCommunityLevel(Opportunity opp, NewstarDealContext dealContext)
    {
        
        if(dealContext==null) {
            dealContext=getDealContext(opp);
        }

        if(dealContext.MarketingCommunity!=null) {
            opp.Name=dealContext.CustomerAccount.Name + ' -  ' + dealContext.MarketingCommunity.Name+' - '+opp.Scenario_Name__c;
  
        } 
    }


    public static void setOpportunitySalesProcess(Opportunity opp, NewstarDealContext dealContext) {
        //assign the correct opportunity record type based on the sales process type picklist value configured on the marketing community
        String oppRecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
                .get(dealContext.MarketingCommunity.Sales_Process_Type__c)
                .getRecordTypeId();

        opp.RecordTypeId=oppRecordTypeId;
    }


    public static void setOpportunityNameAtSubdivisionLevel(Opportunity opp, NewstarDealContext dealContext)
    {
        
        if(dealContext==null) {
            dealContext=getDealContext(opp);
        }

        //set subdivision and lot in the opportunity name, if available
        if(dealContext.Subdivision!=null && dealContext.Lot!=null) {
             opp.Name= dealContext.CustomerAccount.Name + ' -  ' + dealContext.Subdivision.Name +' - Lot '+ dealContext.Lot.Name + ' - '+opp.Scenario_Name__c;
        } 
    }


    public static void setOpportunityAmountsFromDealContext(Opportunity opp, NewstarDealContext dealContext) {

       NewstarDealFinancialInfo financialInfo=new NewstarDealFinancialInfo();
      
       if(dealContext==null) {
            dealContext=getDealContext(opp);
        }

        if(dealContext.Model!=null) {
            financialInfo.BaseModelPrice=dealContext.Model.Price__c;
        }

        if(dealContext.Lot!=null) {
            financialInfo.LotPrice=dealContext.Lot.Price__c;
            financialInfo.LotPremium=dealContext.Lot.Premium__c;
            financialInfo.TotalOptionsAmount=dealContext.Lot.Preconfigured_Options_Amount__c;  

            if(dealContext.Lot.Base_Model_Price_Override__c!=null)
            {
                financialInfo.BaseModelPrice=dealContext.Lot.Base_Model_Price_Override__c;                
            }
        }


        setOpportunityAmounts(opp, financialInfo);
    }


     public static void setOpportunityAmounts(Opportunity opp, NewstarDealFinancialInfo financialInfo) {
        
        if(financialInfo.BaseModelPrice!=null)
            opp.Base_Model_Price__c=financialInfo.BaseModelPrice;
        
        if(financialInfo.LotPrice!=null)
            opp.Lot_Price__c=financialInfo.LotPrice;

        if(financialInfo.LotPremium!=null)
            opp.Lot_Premium__c=financialInfo.LotPremium;

        if(financialInfo.TotalOptionsAmount!=null)
            opp.Total_Options_Amount__c=financialInfo.TotalOptionsAmount;

        if(financialInfo.TotalDiscountAmount!=null)
            opp.Total_Discount_Amount__c=financialInfo.TotalDiscountAmount;

        if(financialInfo.TotalTaxAmount!=null)
            opp.Total_Tax_Amount__c=financialInfo.TotalTaxAmount;

        if(financialInfo.TotalTaxRebateAmount!=null)
            opp.Total_Tax_Rebate_Amount__c=financialInfo.TotalTaxRebateAmount;      

        if(financialInfo.TotalActualSaleAmount!=null)
            opp.Total_Actual_Sale_Amount__c=financialInfo.TotalActualSaleAmount;
      
     } 


    public static NewstarDealContext getDealContext(Opportunity opp) {
      
        NewstarDealContext dealContext=new NewstarDealContext();

        if(opp.Marketing_Community__c!=null) {
          dealContext.MarketingCommunity=[SELECT Id, Name, Sales_Process_Type__c FROM Marketing_Community__c WHERE Id=: opp.Marketing_Community__c LIMIT 1];

        }
      
        if(opp.Subdivision__c!=null){
            dealContext.Subdivision=[SELECT Name FROM Subdivision__c WHERE Id=: opp.Subdivision__c LIMIT 1];
        }
       
        
        if(opp.Lot__c!=null) {
            dealContext.Lot=[SELECT Name, Price__c, Premium__c, Base_Model_Price_Override__c, Preconfigured_Options_Amount__c FROM Lot__c WHERE Id=: opp.Lot__c LIMIT 1];
        } 

        
        if(opp.Model__c!=null) {
            dealContext.Model=[SELECT Name, Price__c FROM Model__c WHERE Id=: opp.Model__c LIMIT 1];
        } 

        dealContext.CustomerAccount=[SELECT Name FROM Account WHERE Id=: opp.AccountId LIMIT 1];

        return dealContext;
    }

}