unpackaged/main/default/objects/Lot__c/Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lot__c/fields/Base_Model_Price_Override__c.field-meta.xml
<CustomField>
        <fullName>Base_Model_Price_Override__c</fullName>
        <label>Base Model Price Override</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Preconfigured_Options_Amount__c.field-meta.xml
<CustomField>
        <fullName>Preconfigured_Options_Amount__c</fullName>
        <label>Preconfigured Options Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Premium__c.field-meta.xml
<CustomField>
        <fullName>Premium__c</fullName>
        <label>Premium</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Price__c.field-meta.xml
<CustomField>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Model__c/fields/Price__c.field-meta.xml
<CustomField>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Base_Model_Price__c.field-meta.xml
<CustomField>
        <fullName>Base_Model_Price__c</fullName>
        <label>Base Model Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lot__c.field-meta.xml
<CustomField>
        <fullName>Lot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Lot</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Lot must belong to the selected subdivision, be available (open) and be released for sale.</errorMessage>
            <filterItems>
                <field>Lot__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <filterItems>
                <field>Lot__c.Released_for_Sale__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Lot__c.Status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Lot__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lot_Premium__c.field-meta.xml
<CustomField>
        <fullName>Lot_Premium__c</fullName>
        <label>Lot Premium</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lot_Price__c.field-meta.xml
<CustomField>
        <fullName>Lot_Price__c</fullName>
        <label>Lot Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Model__c.field-meta.xml
<CustomField>
        <fullName>Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Model must belong to the selected subdivision.</errorMessage>
            <filterItems>
                <field>Model__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Model__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Options_Amount__c.field-meta.xml
<CustomField>
        <fullName>Total_Options_Amount__c</fullName>
        <label>Total Options Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/classes/RefreshOpportunityPricesBatch.cls
global class RefreshOpportunityPricesBatch
	implements
		Database.Batchable<SObject>, 
		Database.AllowsCallouts,
		Database.Stateful {

            global Database.QueryLocator start(Database.BatchableContext bc) {
                System.debug('Executing Salesforce Refresh Opportunity Prices job start...');
               
                return Database.getQueryLocator([SELECT Name, StageName, Base_Model_Price__c, Lot_Price__c, Lot_Premium__c, Total_Options_Amount__c,  
                    		    		 		 Model__r.Name, Model__r.Price__c, Lot__r.Name, Lot__r.Price__c, Lot__r.Premium__c, Lot__r.Base_Model_Price_Override__c, 
                    		   		 			 Lot__r.Preconfigured_Options_Amount__c  
							    				 FROM Opportunity   
							    				 WHERE (StageName = 'Prospecting' OR StageName = 'Engagement')]);
            }            
            
            global void execute(Database.BatchableContext bc, List<Opportunity> scope) {
                System.debug('Executing Salesforce Refresh Opportunity Prices job execute...');

                for(Opportunity s : scope) {

                    if (s.Lot__r.Base_Model_Price_Override__c == null)          
                        s.Base_Model_Price__c = s.Model__r.Price__c;
                    else 
                        s.Base_Model_Price__c = s.Lot__r.Base_Model_Price_Override__c;

                    s.Lot_Price__c = s.Lot__r.Price__c;
                    s.Lot_Premium__c = s.Lot__r.Premium__c;
                    s.Total_Options_Amount__c = s.Lot__r.Preconfigured_Options_Amount__c;
                }    
                
                update scope;
            }
            
            global void finish(Database.BatchableContext bc) {
                System.debug('Finished Salesforce Refresh Opportunity Prices job');
            }
}