unpackaged/main/default/objects/Lot__c/Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lot__c/fields/Assigned_Model__c.field-meta.xml
<CustomField>
        <fullName>Assigned_Model__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assigned Model</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The model should belong to the parent subdivision of the lot.</errorMessage>
            <filterItems>
                <field>Model__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Model__c</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Base_Model_Price_Override__c.field-meta.xml
<CustomField>
        <fullName>Base_Model_Price_Override__c</fullName>
        <label>Base Model Price Override</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Preconfigured_Options_Amount__c.field-meta.xml
<CustomField>
        <fullName>Preconfigured_Options_Amount__c</fullName>
        <label>Preconfigured Options Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Premium__c.field-meta.xml
<CustomField>
        <fullName>Premium__c</fullName>
        <label>Premium</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Price__c.field-meta.xml
<CustomField>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Released_for_Construction__c.field-meta.xml
<CustomField>
        <fullName>Released_for_Construction__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Released for Construction</description>
        <label>Released for Construction</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Released_for_Sale__c.field-meta.xml
<CustomField>
        <fullName>Released_for_Sale__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Released for Sale</description>
        <label>Released for Sale</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Status__c.field-meta.xml
<CustomField>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Street_Address__c.field-meta.xml
<CustomField>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/fields/Type__c.field-meta.xml
<CustomField>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>Spec</fullName>
                </value>
                <value>
                    <fullName>Model</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Model__c/fields/Baths__c.field-meta.xml
<CustomField>
        <fullName>Baths__c</fullName>
        <label>Baths</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Model__c/fields/Beds__c.field-meta.xml
<CustomField>
        <fullName>Beds__c</fullName>
        <label>Beds</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Model__c/fields/Code__c.field-meta.xml
<CustomField>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Model__c/fields/Garages__c.field-meta.xml
<CustomField>
        <fullName>Garages__c</fullName>
        <label>Garages</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Model__c/fields/Half_Baths__c.field-meta.xml
<CustomField>
        <fullName>Half_Baths__c</fullName>
        <label>Half Baths</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Model__c/fields/Newstar_ID__c.field-meta.xml
<CustomField>
        <fullName>Newstar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Newstar ID</label>
        <length>32</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Model__c/fields/Price__c.field-meta.xml
<CustomField>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Model__c/fields/Sq_Ft__c.field-meta.xml
<CustomField>
        <fullName>Sq_Ft__c</fullName>
        <label>Sq. Ft.</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Model__c/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Models</relationshipLabel>
        <relationshipName>Models</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Newstar_Country__c/Newstar_Country__c.object-meta.xml
<CustomObject>
    <label>Newstar Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Newstar Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Newstar_State__c/Newstar_State__c.object-meta.xml
<CustomObject>
    <label>NEWSTAR States</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NEWSTAR States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Newstar_State__c/fields/Code__c.field-meta.xml
<CustomField>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Newstar_State__c/fields/Newstar_Country__c.field-meta.xml
<CustomField>
        <fullName>Newstar_Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>NEWSTAR Country</label>
        <referenceTo>Newstar_Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Sales_Agent__c/Sales_Agent__c.object-meta.xml
<CustomObject>
    <label>Sales Agent</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Agent__c/fields/First_Name__c.field-meta.xml
<CustomField>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Sales_Agent__c/fields/Newstar_ID__c.field-meta.xml
<CustomField>
        <fullName>Newstar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Newstar ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

unpackaged/main/default/objects/Sales_Office__c/Sales_Office__c.object-meta.xml
<CustomObject>
    <description>NEWSTAR Sales Office</description>
    <label>Sales Office</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAgentSalesOfficeLink__c/SalesAgentSalesOfficeLink__c.object-meta.xml
<CustomObject>
    <label>Sales Agent Sales Office Relationship</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agent Sales Office Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAgentSalesOfficeLink__c/fields/Sales_Agent__c.field-meta.xml
<CustomField>
        <fullName>Sales_Agent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Agent</label>
        <referenceTo>Sales_Agent__c</referenceTo>
        <relationshipLabel>Sales Agent Sales Office Relationships</relationshipLabel>
        <relationshipName>Sales_Agent_Sales_Office_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/SalesAgentSalesOfficeLink__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Sales Agent Sales Office Relationships</relationshipLabel>
        <relationshipName>Sales_Agent_Sales_Office_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/Subdivision__c.object-meta.xml
<CustomObject>
    <description>NEWSTAR Sales Subdivision</description>
    <label>Subdivision</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subdivisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subdivision__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/NewstarMasterDataApiService.cls
public with sharing class NewstarMasterDataApiService {
    

    /*
        Pulls all NEWSTAR geography data (countries/states) into Salesforce.
    */
    public static void ProcessGeographyLayout(NewstarClient newstarClient) {
        

        NewstarGeographyLayoutApi geoApi=new NewstarGeographyLayoutApi(newstarClient);
        NewstarPagedResultCountry countryPagedResult=geoApi.get();

        List<Newstar_Country__c> countries=new List<Newstar_Country__c>();
        Schema.SObjectField countryNewstarIdField = Newstar_Country__c.Fields.Newstar_ID__c;

        List<Newstar_State__c> states=new List<Newstar_State__c>();
        Schema.SObjectField stateNewstarIdField = Newstar_State__c.Fields.Newstar_ID__c;

        for (NewstarCountry apiCountry : countryPagedResult.data) {
       
            Newstar_Country__c country=new Newstar_Country__c();

            country.Name=apiCountry.name;
            country.Newstar_ID__c=String.valueOf(apiCountry.Id);
    
            countries.add(country);

            //process provinces of the current country
            if(apiCountry.statesProvinces!=null) {

                for (NewstarStateProvince apiStateProvince : apiCountry.statesProvinces) {
                    Newstar_State__c state=new Newstar_State__c();
                    
                    state.Name=apiStateProvince.name;
                    state.Code__c=apiStateProvince.code;
                    state.Newstar_ID__c=String.valueOf(apiStateProvince.Id);

                    //construct reference back to the parent country
                    state.Newstar_Country__r=new Newstar_Country__c(Newstar_ID__c=country.Newstar_ID__c);

                    states.add(state);
                }
            }
        }

        //commit both countries and provinces together

        SavePoint sp = Database.setSavePoint();
        try {
          Database.upsert(countries, countryNewstarIdField, true);
          Database.upsert(states, stateNewstarIdField, true);
          
        } 
        catch (Exception e) {
        
            Database.rollback(sp);

            // Throw exception on to caller
            throw e;
        }

    }




    /*
        Pulls all NEWSTAR sales agents and upserts sales agent data into Salesforce.
    */
    public static void ProcessSalesAgents(NewstarClient newstarClient) {
        
        NewstarSalesAgentApi salesAgentApi=new NewstarSalesAgentApi(newstarClient);
        NewstarPagedResultSalesAgent salesAgentPagedResult=salesAgentApi.get();

        List<Sales_Agent__c> salesAgents=new List<Sales_Agent__c>();
        Schema.SObjectField newstarIdField = Sales_Agent__c.Fields.Newstar_ID__c;

        for (NewstarSalesAgent apiSalesAgent : salesAgentPagedResult.data) {
       
            Sales_Agent__c salesAgent=new Sales_Agent__c();

            salesAgent.Name=string.valueOf(apiSalesAgent.firstName) + ' ' + string.valueOf(apiSalesAgent.lastName);
            salesAgent.First_Name__c = string.valueOf(apiSalesAgent.firstName);
            salesAgent.Last_Name__c = string.valueOf(apiSalesAgent.lastName);
            salesAgent.Newstar_ID__c=String.valueOf(apiSalesAgent.Id);
                
            salesAgents.add(salesAgent);
        }

        Database.upsert(salesAgents, newstarIdField, true);

    }


     /*
        Pulls all NEWSTAR sales offices and sales office<->sales agents relationships 
        and upserts sales office data into Salesforce.
    */
    public static void ProcessSalesOffices(NewstarClient newstarClient) {
        
        NewstarSalesOfficeApi salesOfficeApi=new NewstarSalesOfficeApi(newstarClient);
        NewstarPagedResultSalesOffice salesOfficePagedResult=salesOfficeApi.get();

        List<Sales_Office__c> salesOffices=new List<Sales_Office__c>();
        Schema.SObjectField newstarIdField = Sales_Office__c.Fields.Newstar_ID__c;
        
        List<SalesAgentSalesOfficeLink__c> salesAgentSalesOfficeLinks=new List<SalesAgentSalesOfficeLink__c>();
        Schema.SObjectField salesAgentSalesOfficeLinkNewstarIdField = SalesAgentSalesOfficeLink__c.Fields.Newstar_ID__c;

        //iterate the sales office received from the API
        for (NewstarSalesOffice apiSalesOffice : salesOfficePagedResult.data) {
       
            //setup the sales office SF object
            Sales_Office__c salesOffice=new Sales_Office__c();

            //set name
            salesOffice.Name=apiSalesOffice.name;

            //set SO NEWSTAR ID
            salesOffice.Newstar_ID__c=String.valueOf(apiSalesOffice.Id);
                
            salesOffices.add(salesOffice);

            
            //check if sales office<->sales agent relationships data is included for the sales office...
            if(apiSalesOffice.salesAgents!=null) {

                //if so, iterate the relationship records from the API and build appropriate SF objects
                for (NewstarSalesOfficeSalesAgentRelation newstarSalesOfficeSalesAgentRelation : apiSalesOffice.salesAgents) {       

                    SalesAgentSalesOfficeLink__c salesAgentSalesOfficeLink = new SalesAgentSalesOfficeLink__c();

                    //configure a relationship to the sales agent
                    Sales_Agent__c salesAgent = new Sales_Agent__c(Newstar_ID__c=String.valueOf(newstarSalesOfficeSalesAgentRelation.userId));
                    
                    salesAgentSalesOfficeLink.Name = salesAgent.Name;
                    salesAgentSalesOfficeLink.Sales_Agent__r = salesAgent;

                    //configure the relationship to sales office being processed
                    salesAgentSalesOfficeLink.Sales_Office__r = new Sales_Office__c(Newstar_ID__c=String.valueOf(apiSalesOffice.id));
                    
                    //the NEWSTAR ID of the relationship object refers to the ID  of the relationship in SOUsers in NSS
                    salesAgentSalesOfficeLink.Newstar_ID__c=String.valueOf(newstarSalesOfficeSalesAgentRelation.id);

                    salesAgentSalesOfficeLinks.add(salesAgentSalesOfficeLink);
                }
            }
        }


        //commit sales offices and SO<->sales agent relationships
        SavePoint sp = Database.setSavePoint();

        try {

            Database.upsert(salesOffices, newstarIdField, true);
            Database.upsert(salesAgentSalesOfficeLinks, salesAgentSalesOfficeLinkNewstarIdField, true);
        } 
        catch (Exception e) {
        
            Database.rollback(sp);
            throw e;
        }
       
    }



    /*
        Pulls all NEWSTAR subdivisions and upserts subdivision data into Salesforce.
    */
    public static void ProcessSubdivisions(NewstarClient newstarClient) {
        
        Map<String, Object> subdivisionApiParams=new Map<String, Object>();
        //subdivisionApiParams.put('salesOfficeId',0);
        subdivisionApiParams.put('includeInactive', true);

        NewstarSubdivisionApi subdivisionApi=new NewstarSubdivisionApi(newstarClient);
        NewstarPagedResultSubdivision  subdivisionPagedResult=subdivisionApi.get(subdivisionApiParams);

        List<Subdivision__c> subdivisions=new List<Subdivision__c>();
        Schema.SObjectField newstarIdField = Subdivision__c.Fields.Newstar_ID__c;

        for (NewstarSubdivision apiSubdivision : subdivisionPagedResult.data) {
       
            Subdivision__c subdivision=new Subdivision__c();

            subdivision.Name=apiSubdivision.name;
            subdivision.Newstar_ID__c=String.valueOf(apiSubdivision.Id);

            //construct reference to parent Sales Office using SO's external ID
            Sales_Office__c parentSalesOffice=new Sales_Office__c(Newstar_ID__c=String.valueOf(apiSubdivision.salesOfficeId));
            subdivision.Sales_Office__r=parentSalesOffice;

            subdivisions.add(subdivision);
        }

        Database.upsert(subdivisions, newstarIdField, true);

    }


    public static void ProcessSubdivisionModelsForBatch(NewstarClient newstarClient, List<Subdivision__c> subdivisionBatch) {
        
        List<Model__c> models=new List<Model__c>();
        Schema.SObjectField newstarIdField = Model__c.Fields.Newstar_ID__c;

        for(Subdivision__c subdivision: subdivisionBatch) {
            models.addAll(NewstarMasterDataApiService.GetProcessedSubdivisionModels(newstarClient, subdivision));
        }

        Database.upsert(models, newstarIdField, true);
    }  

    
    private static List<Model__c> GetProcessedSubdivisionModels(NewstarClient newstarClient, Subdivision__c subdivision) {
        
        Map<String, Object> modelApiParams=new Map<String, Object>();
        modelApiParams.put('subdivisionId', Integer.valueOf(subdivision.Newstar_ID__c));

        NewstarModelApi modelApi=new NewstarModelApi(newstarClient);
        NewstarPagedResultModel  modelPagedResult=modelApi.get(modelApiParams);

        List<Model__c> models=new List<Model__c>();
     
        for (NewstarModel apiModel : modelPagedResult.data) {
       
            Model__c model=new Model__c();

            //model code as either pure code of code-elevation combination
            model.Code__c=apiModel.code;
            if(apiModel.elevation!=null && apiModel.elevation!='') {
                    model.Code__c=model.Code__c+'-'+apiModel.elevation;
            }

            //name
            model.Name=apiModel.name;

            //NEWSTAR ID
            model.Newstar_ID__c=String.valueOf(apiModel.Id);

            //base model product attributes
            model.Beds__c=apiModel.bedrooms;
            model.Baths__c=apiModel.fullBaths;
            model.Half_Baths__c=apiModel.halfBaths;
            model.Garages__c=apiModel.garageCapacity;
            model.Price__c=apiModel.baseModelPrice;
            model.Sq_Ft__c=apiModel.squareFootage;
            
           
            
            //construct reference to parent subdivision
            model.Subdivision__c=subdivision.Id;

            models.add(model);
        }

        return models;

    }


    public static void ProcessSubdivisionLotsForBatch(NewstarClient newstarClient, List<Subdivision__c> subdivisionBatch) {
        
        List<Lot__c> lots=new List<Lot__c>();
        Schema.SObjectField newstarIdField = Lot__c.Fields.Newstar_ID__c;

        
        for(Subdivision__c subdivision: subdivisionBatch) {
            lots.addAll(NewstarMasterDataApiService.GetProcessedSubdivisionLots(newstarClient, subdivision));
        }

        Database.upsert(lots, newstarIdField, true);
    }



    private static List<Lot__c> GetProcessedSubdivisionLots(NewstarClient newstarClient, Subdivision__c subdivision) {
        
        Map<String, Object> lotApiParams=new Map<String, Object>();
        lotApiParams.put('subdivisionId', Integer.valueOf(subdivision.Newstar_ID__c));

        NewstarLotApi lotApi=new NewstarLotApi(newstarClient);
        NewstarPagedResultLot  lotPagedResult=lotApi.get(lotApiParams);

        List<Lot__c> lots=new List<Lot__c>();
    
        for (NewstarLot apiLot : lotPagedResult.data) {
       
            Lot__c lot=new Lot__c();

            //name, NEWSTAR ID and last sync
            lot.Name=apiLot.lotNumber;
            lot.Newstar_ID__c=String.valueOf(apiLot.Id);

            //resolve lot type 
            lot.Type__c=NewstarDataConversionHelper.normalizeEnumValue(apiLot.lotType.name());
            
            //override availability status to treat UNKNOWN as OPEN and OFFER as SOLD
            if(apiLot.availabilityStatus==NewstarLot.AvailabilityStatusEnum.UNKNOWN){
                apiLot.availabilityStatus=NewstarLot.AvailabilityStatusEnum.OPEN;
            }
            else if(apiLot.availabilityStatus==NewstarLot.AvailabilityStatusEnum.OFFER){
                apiLot.availabilityStatus=NewstarLot.AvailabilityStatusEnum.SOLD;
            }

            //resolve availability status
            lot.Status__c=NewstarDataConversionHelper.normalizeEnumValue(apiLot.availabilityStatus.name());


            //option total (based on LOA builder-approved options) for UNsold spec and model lots
            if((apiLot.lotType==NewstarLot.LotTypeEnum.SPEC 
                || apiLot.lotType==NewstarLot.LotTypeEnum.MODEL)
                && apiLot.availabilityStatus==NewstarLot.AvailabilityStatusEnum.OPEN)
                 {
                   lot.Preconfigured_Options_Amount__c=apiLot.totalOptionsAmount; 
                }

            //set pre-assigned model
            if(apiLot.modelId!=null && apiLot.modelId>0){

                Model__c assignedModelRef=new Model__c(Newstar_ID__c=String.valueOf(apiLot.modelId));
                lot.Assigned_Model__r=assignedModelRef;       
            }
            
             //construct reference to parent subdivision
            lot.Subdivision__c=subdivision.Id;

            //street address
            lot.Street_Address__c=apiLot.address;
            
            //flag indicating if released for sale - used for filtering
            lot.Released_For_Sale__c = apiLot.releasedForSale;

            //flag indicating if released for construction - for information only
            lot.Released_For_Construction__c = apiLot.releasedForConstruction;

            lot.Price__c = apiLot.basePrice;
            lot.Premium__c = apiLot.premium;
            lot.Base_Model_Price_Override__c = apiLot.baseModelPriceOverride;

            lots.add(lot);
        }

        return lots;

    }




    

}