unpackaged/main/default/objects/Cobuyer__c/Cobuyer__c.object-meta.xml
<CustomObject>
    <label>Cobuyer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cobuyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Cobuyer__c/fields/Newstar_ID__c.field-meta.xml
<CustomField>
        <fullName>Newstar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Newstar ID</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Cobuyer__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </RecordType>

unpackaged/main/default/objects/Contact/fields/Newstar_ID__c.field-meta.xml
<CustomField>
        <fullName>Newstar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Newstar ID</label>
        <length>25</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Lot__c/Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lot__c/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Marketing_Community__c/Marketing_Community__c.object-meta.xml
<CustomObject>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Marketing_Community__c/fields/Sales_office__c.field-meta.xml
<CustomField>
        <fullName>Sales_office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Marketing Communities</relationshipLabel>
        <relationshipName>Marketing_Communities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Model__c/fields/Newstar_ID__c.field-meta.xml
<CustomField>
        <fullName>Newstar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Newstar ID</label>
        <length>32</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Model__c/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Models</relationshipLabel>
        <relationshipName>Models</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Home_Swing__c.field-meta.xml
<CustomField>
        <fullName>Home_Swing__c</fullName>
        <label>Home Swing</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Left</fullName>
                    <default>true</default>
                    <label>Left</label>
                </value>
                <value>
                    <fullName>Right</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lot__c.field-meta.xml
<CustomField>
        <fullName>Lot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Lot</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Lot must belong to the selected subdivision, be available (open) and be released for sale.</errorMessage>
            <filterItems>
                <field>Lot__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <filterItems>
                <field>Lot__c.Released_for_Sale__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Lot__c.Status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Lot__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lot_Hold_Expiry_Date__c.field-meta.xml
<CustomField>
        <fullName>Lot_Hold_Expiry_Date__c</fullName>
        <label>Lot Hold Expiry Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Model__c.field-meta.xml
<CustomField>
        <fullName>Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Model must belong to the selected subdivision.</errorMessage>
            <filterItems>
                <field>Model__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Model__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Newstar_ID__c.field-meta.xml
<CustomField>
        <fullName>Newstar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Newstar ID</label>
        <length>25</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Scenario_Name__c.field-meta.xml
<CustomField>
        <fullName>Scenario_Name__c</fullName>
        <label>Scenario Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Subdivision must belong to the selected sales office and the selected marketing community.</errorMessage>
            <filterItems>
                <field>Subdivision__c.Sales_Office__c</field>
                <operation>equals</operation>
                <valueField>$Source.Sales_Office__c</valueField>
            </filterItems>
            <filterItems>
                <field>Subdivision__c.Marketing_Community__c</field>
                <operation>equals</operation>
                <valueField>$Source.Marketing_Community__c</valueField>
            </filterItems>
            <infoMessage>Select a subdivision</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Sales_Agent__c/Sales_Agent__c.object-meta.xml
<CustomObject>
    <label>Sales Agent</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Agent__c/fields/Newstar_ID__c.field-meta.xml
<CustomField>
        <fullName>Newstar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Newstar ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

unpackaged/main/default/objects/Sales_Office_Customer__c/Sales_Office_Customer__c.object-meta.xml
<CustomObject>
    <label>Sales Office Customer</label>
    <nameField>
        <displayFormat>SOC-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Office Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Office_Customer__c/fields/Newstar_ID__c.field-meta.xml
<CustomField>
        <fullName>Newstar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Newstar ID</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

unpackaged/main/default/objects/Sales_Office_Customer__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Sales Office Customers</relationshipLabel>
        <relationshipName>Sales_Office_Customers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/SalesAgentSalesOfficeLink__c/SalesAgentSalesOfficeLink__c.object-meta.xml
<CustomObject>
    <label>Sales Agent Sales Office Relationship</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agent Sales Office Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAgentSalesOfficeLink__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Sales Agent Sales Office Relationships</relationshipLabel>
        <relationshipName>Sales_Agent_Sales_Office_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/Subdivision__c.object-meta.xml
<CustomObject>
    <description>NEWSTAR Sales Subdivision</description>
    <label>Subdivision</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subdivisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subdivision__c/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/NewstarContractInformationService.cls
/*
    Provides helper methods to access opportunity, customers, etc. data
    associated with contract and customer operations.
*/
public  class NewstarContractInformationService {
   
  /*
    Returns the opportunity object given the specified ID
    and includes the fields necessary for typical NEWSTAR integration scenarios.
  */ 
  public static Opportunity getOpportunity(Id opportunityId) {

       Opportunity opp=[SELECT 
            Id,
            Name, 
            StageName, 
            CloseDate,
            Marketing_Community__c,
            Sales_Office__c, 
            Subdivision__c, 
            Model__c, 
            Lot__c, 
            Lot_Hold_Expiry_Date__c,
            Home_Swing__c,
            Newstar_ID__c,
            Scenario_Name__c,
            Account.Id,
            Sales_Agent_Sales_Office_Relationship__c,
            Sales_Agent_Sales_Office_Relationship__r.Sales_Agent__c,
            Account.FirstName,
            Account.LastName,
            Account.PersonMailingAddress,
            Account.PersonEmail,
            Account.Phone,
            Account.PersonMobilePhone,
            Account.PersonHomePhone,
            Subdivision__r.Newstar_ID__c,
            Subdivision__r.Sitemap_URL__c,
            Model__r.Newstar_ID__c,
            Lot__r.Newstar_ID__c,
            Real_Estate_Agent__c,
            Real_Estate_Agent__r.Newstar_ID__c
            FROM Opportunity 
            WHERE Id=: opportunityId
            LIMIT 1];
      
         return opp;
    }


    
    /*
        Returns a person account<->sales office junction object
        based on the sales office selected on the supplied opportunity
        and the person account as the opportunity's parent.
    */
    public static Sales_Office_Customer__c getCustomerSalesOfficeJunction(Opportunity opp) {

        Sales_Office_Customer__c customerSalesOfficeJunction=null;
        
        //get the junction object that represents an association between
        //the customer's person account object and a NEWSTAR Sales sales office object
        List<Sales_Office_Customer__c> junctions=
            [
                SELECT 
                Id, 
                Sales_Office__c,
                Account__c,
                Newstar_ID__c
                FROM 
                Sales_Office_Customer__c 
                WHERE 
                Account__c =: opp.Account.Id
                AND
                Sales_Office__c =: opp.Sales_Office__c
                LIMIT 1
            ];

        if(junctions.size()==0) {
            //junction object does not exist, a new junction object needs to be created

            customerSalesOfficeJunction=new Sales_Office_Customer__c();
            
            customerSalesOfficeJunction.Sales_Office__c=opp.Sales_Office__c;
            customerSalesOfficeJunction.Account__c=opp.Account.Id;
          
        }
        else {
            customerSalesOfficeJunction=junctions[0];
        }


        return customerSalesOfficeJunction;

    }



  

    /*
        Returns the sales agent assigned to the opportunity
        via the junction sales agent<->sales office entity.
    */
    public static Sales_Agent__c getSalesAgentFromOpportunity(Opportunity opp) {

        if(opp.Sales_Agent_Sales_Office_Relationship__r.Sales_Agent__c==null){
            return null;
        }

        Sales_Agent__c salesAgent=[
            SELECT 
            Id,
            Name,
            Newstar_ID__c
            FROM Sales_Agent__c
            WHERE Id=: opp.Sales_Agent_Sales_Office_Relationship__r.Sales_Agent__c
        ];

        return salesAgent;
    }


    /*
        Returns a NEWSTAR State object based on the free-form address in the customer's person account.
    */
    public static Newstar_State__c getNewstarStateAndCountry(Account customerAccount) {

        Address address=customerAccount.PersonMailingAddress;

        String stateProvinceCode=address.StateCode.trim().toUpperCase();
        String countryName=address.Country.trim();

        List<Newstar_State__c> states=
        [
            SELECT
            Id,
            Name,
            Newstar_ID__c,
            Newstar_Country__r.Newstar_ID__c
            
            FROM
            Newstar_State__c
            WHERE
            Code__c=: stateProvinceCode
            AND
            Newstar_Country__r.Name=: countryName
            LIMIT 1
        ];

        if(states.size()!=1)
            return null;

        return states[0];
    }



    /*
        Returns the specified Person Account representing the customer
        together with a list of child junction objections used to list
        the sales offices the account is associated with in NEWSTAR Sales.
    */
    public static Account getCustomerWithSalesOffices(Id customerAccountId) {

        List<Account> accounts=[

            SELECT 
                Id, 
                Name, 
                FirstName, 
                LastName,
                PersonMailingAddress,
                PersonEmail,
                Phone,
                PersonMobilePhone,
                PersonHomePhone,
                (
                    SELECT 
                        Id, 
                        Name,
                        Newstar_ID__c,
                        Newstar_Sync_Status__c, 
                        Sales_Office__c, 
                        Sales_Office__r.Name
                    FROM 
                        Sales_Office_Accounts__r
                )
            FROM Account
            WHERE Id =: customerAccountId
        ] ;

        if(accounts.size()==1) {
            return accounts[0];
        }
        
        return null;
    }


    public static Cobuyer__c getCobuyer(Id cobuyerId) {

        List<Cobuyer__c> cobuyers=[

            SELECT
                Id,
                Name,
                First_Name__c,
                Last_Name__c,
                Newstar_ID__c,
                Opportunity__r.Newstar_ID__c
            FROM
                Cobuyer__c
            WHERE
                Id =: cobuyerId

            LIMIT 1
        ];

        if(cobuyers.size()==1) {
            return cobuyers[0];
        }

        return null;

    }
}