unpackaged/main/default/objects/Cobuyer__c/Cobuyer__c.object-meta.xml
<CustomObject>
    <label>Cobuyer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cobuyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Cobuyer__c/fields/Interest_List__c.field-meta.xml
<CustomField>
        <fullName>Interest_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interest List</label>
        <referenceTo>Interest_List__c</referenceTo>
        <relationshipLabel>Cobuyers</relationshipLabel>
        <relationshipName>Cobuyers</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Cobuyer__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </RecordType>

unpackaged/main/default/objects/Interest_List__c/Interest_List__c.object-meta.xml
<CustomObject>
    <label>Interest List</label>
    <nameField>
        <label>Interest List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Interest_List__c/fields/Lead__c.field-meta.xml
<CustomField>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Lead_source__c.field-meta.xml
<CustomField>
        <fullName>Lead_source__c</fullName>
        <label>Lead source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advertisement</fullName>
                </value>
                <value>
                    <fullName>Austin Relocation Guide</fullName>
                </value>
                <value>
                    <fullName>BDX</fullName>
                </value>
                <value>
                    <fullName>Billboard</fullName>
                </value>
                <value>
                    <fullName>Brookfield Website</fullName>
                </value>
                <value>
                    <fullName>Builder Boost</fullName>
                </value>
                <value>
                    <fullName>Customer Event</fullName>
                </value>
                <value>
                    <fullName>Direct Mail</fullName>
                </value>
                <value>
                    <fullName>Driving By</fullName>
                </value>
                <value>
                    <fullName>Employee Referral</fullName>
                </value>
                <value>
                    <fullName>External Referral</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Facebook Lead Ad</fullName>
                </value>
                <value>
                    <fullName>Hot On Homes</fullName>
                </value>
                <value>
                    <fullName>Interactive Sales Tool</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Landing Page</fullName>
                </value>
                <value>
                    <fullName>Lightbox</fullName>
                </value>
                <value>
                    <fullName>Live Chat</fullName>
                </value>
                <value>
                    <fullName>Master Plan/Community</fullName>
                </value>
                <value>
                    <fullName>Newspaper/Magazine</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Paid Search</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Partner Referral</fullName>
                </value>
                <value>
                    <fullName>PCR</fullName>
                </value>
                <value>
                    <fullName>Phone Inquiry</fullName>
                </value>
                <value>
                    <fullName>Radio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Rank__c.field-meta.xml
<CustomField>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A - Ready, Willing, Able</fullName>
                </value>
                <value>
                    <fullName>B - Two of These</fullName>
                </value>
                <value>
                    <fullName>C - Ready or Willing or Able</fullName>
                </value>
                <value>
                    <fullName>D - Cold</fullName>
                </value>
                <value>
                    <fullName>M - Marketing Only</fullName>
                </value>
                <value>
                    <fullName>W - Web Lead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Realtor__c.field-meta.xml
<CustomField>
        <fullName>Realtor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Realtor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Real_Estate_Agent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interest List (Realtor)</relationshipLabel>
        <relationshipName>Interest_List1</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Stage__c.field-meta.xml
<CustomField>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Lead Lost</fullName>
                </value>
                <value>
                    <fullName>Triage for Marketing</fullName>
                    <isActive>false</isActive>
                    <label>Triage for Marketing</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <isActive>false</isActive>
                    <label>Unqualified</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Converted_From_Lead__c.field-meta.xml
<CustomField>
        <fullName>Converted_From_Lead__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Converted From Lead</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Realtor__c.field-meta.xml
<CustomField>
        <fullName>Realtor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Are You a Realtor?</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Marketing_Community__c/Marketing_Community__c.object-meta.xml
<CustomObject>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Marketing_Community__c/fields/Sales_office__c.field-meta.xml
<CustomField>
        <fullName>Sales_office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Marketing Communities</relationshipLabel>
        <relationshipName>Marketing_Communities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Converted_From_Lead__c.field-meta.xml
<CustomField>
        <fullName>Converted_From_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted From Lead</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Subdivision must belong to the selected sales office and the selected marketing community.</errorMessage>
            <filterItems>
                <field>Subdivision__c.Sales_Office__c</field>
                <operation>equals</operation>
                <valueField>$Source.Sales_Office__c</valueField>
            </filterItems>
            <filterItems>
                <field>Subdivision__c.Marketing_Community__c</field>
                <operation>equals</operation>
                <valueField>$Source.Marketing_Community__c</valueField>
            </filterItems>
            <infoMessage>Select a subdivision</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/Subdivision__c.object-meta.xml
<CustomObject>
    <description>NEWSTAR Sales Subdivision</description>
    <label>Subdivision</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subdivisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subdivision__c/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/LeadConvertController.cls
public inherited sharing class LeadConvertController
{
    public static Map<String, Schema.RecordTypeInfo> CobuyerRecordTypeaMap = cobuyer__c.SObjectType.getDescribe().getRecordTypeInfosByName();
    public static map<id,integer> mpOpp=new map<id,integer>();
    
    @Auraenabled
    public static Id leadconvert(Id LeadId)
    {   
        Database.LeadConvertResult lcr=convertLead(leadId);
        if(lcr.isSuccess())
        {
            Id AccountId=lcr.getAccountId();
            Account acc=[select Id, recordtypeId from  Account where Id=: AccountId];
            acc.recordtypeId=account.SObjectType.getDescribe().getRecordTypeInfosByName().get('Customer').getRecordTypeId();
            update acc;
            list<Opportunity> lstOpp=createOpportunities(leadId, AccountId);
            return AccountId;
        }
        return null;
    }
    
    // Convert Lead and create a new Account and Opportunity
    private static Database.LeadConvertResult convertLead(Id leadId)
    {
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(leadId);
        lc.setDoNotCreateOpportunity(true);
        lc.setConvertedStatus(convertStatus.MasterLabel);
        system.debug('Before lead convert');
        try{
            system.debug('Inside Lead convert');
            return Database.convertLead(lc);
        }
        catch (Exception ex) {
            System.debug('@@@@ - convert error: ' + ex.getMessage());
           // ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error,string.valueof(ex));
            //ApexPages.addMessage(myMsg);
            throw new AuraHandledException('Error Exception happend'+ex.getMessage());           
            //return null;
        }
    }


  /* convert Interest Lists to Opportunities and change cobuyer recordtype to Opporttunity*/
    private static list<Opportunity> createOpportunities(Id leadId,Id acct)
    {
        //List<Interest_list__c> lstIntLst=[select Id, Name, stage__c,rank__c,lead_source__c from Interest_list__c where Lead__c =: ld.Id];
        List<Opportunity> lstOpp=new list<Opportunity>();
        Set<Id> setIntlst= new Set<Id>();

        integer index=0;
        list<contact> lstContact= [select Id from Contact where accountid=: acct];
        list<Interest_list__c> lstIntLst=[select Id, Name, stage__c,lead_source__c,marketing_community__c,Sales_Office__c,lead__r.Name,
        Subdivision__c,subdivision__r.name,Realtor__c from Interest_list__c where Lead__c =: leadId];
        Validate(lstIntLst);
        try
        {
        for(Interest_list__c intLst:lstIntLst)
        {
           Opportunity opp=new Opportunity();
           opp.accountId=acct;
           string oppname=IntLst.Lead__r.name + ' - ' + Cachedcollections.mysubdivisionIdMap.get(IntLst.subdivision__c);
           system.debug(' Opportunity name: ' + oppname);
           system.debug(' Subdivision name: ' + IntLst.subdivision__c);
           system.debug(' Cached Subdivision name: ' + Cachedcollections.mysubdivisionIdMap.get(IntLst.subdivision__c));
           opp.name=oppname;
           opp.marketing_community__c=intLst.marketing_community__C;
           opp.StageName='Prospecting';//intlst.stage__c;
           if (intLst.lead_source__c!= '')
               opp.LeadSource=intLst.lead_source__c;
           opp.closeDate=date.today().addDays(60); /* Look into target close date in newstar*/
           opp.Converted_From_Lead__c=true;
           if (intLst.Realtor__c!= '')
               opp.Real_Estate_Agent__c=intLst.Realtor__c;
           opp.Sales_Office__c=intLst.Sales_Office__c;
           opp.Scenario_Name__c='Default Scenario';
           if(intlst.Subdivision__c!=null)
               opp.Subdivision__c=intlst.Subdivision__c;
           setIntlst.add(intlst.Id);
           mpopp.put(intlst.Id, index);
           index++;
           lstopp.add(opp);
        }
        insert lstOpp;
        list<cobuyer__c> lstCobuyer = [select Id,recordtypeId,Opportunity__c,interest_list__c from Cobuyer__c where Interest_list__c in :setIntlst];
        //list<beback__c> lstnotes = [select Id,Opportunity__c,Community_of_Interest__c from beback__c where Community_of_Interest__c in :setIntlst];
        for(Cobuyer__c coby:lstCobuyer )
        {
            coby.recordtypeId=CobuyerRecordTypeaMap.get('Opportunity').getRecordTypeId();
            if(mpopp.containskey(coby.interest_list__c))
            {
               // system.debug('index' + mpopp.get(coby.interest_list__c));
              //  system.debug('Opportunity list:' + lstOpp);
                coby.opportunity__c=lstOpp[mpopp.get(coby.interest_list__c)].Id;
            }
        }
        update lstCobuyer;
        /*for(beback__c n: lstnotes)
        {
            if(mpopp.containskey(n.Community_of_Interest__c))
            {
               // system.debug('index' + mpopp.get(coby.interest_list__c));
              //  system.debug('Opportunity list:' + lstOpp);
                n.opportunity__c=lstOpp[mpopp.get(n.Community_of_Interest__c)].Id;
            }
        }
        update lstnotes;*/
        list<OpportunityContactRole> lstoppconrole=new list<OpportunityContactRole>();
        for(Opportunity opp : lstOpp)
        {
            OpportunityContactRole ocr = new OpportunityContactRole();
            ocr.OpportunityId = opp.Id;
            ocr.ContactId = lstcontact[0].Id;
            ocr.Role = 'Primary Buyer';
            lstoppconrole.add(ocr);
        }
        insert lstoppconrole;
        //account = [Select Id, PersonContactId from Account where Id=: account.Id];
        }
        catch(exception ex)
        {
            throw new AuraHandledException('Error Exception happend'+ex.getMessage());
        }
        return lstOpp;
    }
    private static void Validate(List<Interest_List__c> lstIntLst)
    {
        for(Interest_list__c intLst:lstIntLst)
        {
            if (intLst.stage__c == null) 
                { 
                    //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please enter value')); 
                }  
        }
    }
   private static void addToOpportunityRole(String personContactId, 
                                            String oppId, 
                                            String role)
    {
       
    }  
}