unpackaged/main/default/objects/Account/fields/Marketing_Division__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Division</label>
        <referenceTo>Marketing_Division__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Cobuyer__c/Cobuyer__c.object-meta.xml
<CustomObject>
    <label>Cobuyer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cobuyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Cobuyer__c/fields/Interest_List__c.field-meta.xml
<CustomField>
        <fullName>Interest_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interest List</label>
        <referenceTo>Interest_List__c</referenceTo>
        <relationshipLabel>Cobuyers</relationshipLabel>
        <relationshipName>Cobuyers</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Cobuyer__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </RecordType>

unpackaged/main/default/objects/Interest_List__c/Interest_List__c.object-meta.xml
<CustomObject>
    <label>Interest List</label>
    <nameField>
        <label>Interest List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Interest_List__c/fields/Interest_Status__c.field-meta.xml
<CustomField>
        <fullName>Interest_Status__c</fullName>
        <label>Interest Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Stage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Responded</fullName>
                </value>
                <value>
                    <fullName>Responded Nurture</fullName>
                </value>
                <value>
                    <fullName>Unattended Tour</fullName>
                </value>
                <value>
                    <fullName>Confirmed Appointment</fullName>
                </value>
                <value>
                    <fullName>Missed Appointment</fullName>
                </value>
                <value>
                    <fullName>Site Visited</fullName>
                </value>
                <value>
                    <fullName>Contingent</fullName>
                </value>
                <value>
                    <fullName>Purchased</fullName>
                </value>
                <value>
                    <fullName>Prequalified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Lead__c.field-meta.xml
<CustomField>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Stage__c.field-meta.xml
<CustomField>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Lead Lost</fullName>
                </value>
                <value>
                    <fullName>Triage for Marketing</fullName>
                    <isActive>false</isActive>
                    <label>Triage for Marketing</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <isActive>false</isActive>
                    <label>Unqualified</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Community_Text__c.field-meta.xml
<CustomField>
        <fullName>Community_Text__c</fullName>
        <description>To hold the community information from the web to lead form</description>
        <label>Community Interested In</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Is_Hubspot_lead__c.field-meta.xml
<CustomField>
        <fullName>Is_Hubspot_lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is  Hubspot lead</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Marketing_Division__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Division</label>
        <referenceTo>Marketing_Division__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Marketing_Community__c/Marketing_Community__c.object-meta.xml
<CustomObject>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Marketing_Community__c/fields/Assigned_Queue__c.field-meta.xml
<CustomField>
        <fullName>Assigned_Queue__c</fullName>
        <label>Assigned Queue</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Toronto_Pathways</fullName>
                </value>
                <value>
                    <fullName>Toronto_Pinehurst</fullName>
                </value>
                <value>
                    <fullName>Toronto_Woodhaven</fullName>
                </value>
                <value>
                    <fullName>DC_Avendale</fullName>
                </value>
                <value>
                    <fullName>DC_Admirals_Square</fullName>
                </value>
                <value>
                    <fullName>DC_Bradford_s_Landing</fullName>
                </value>
                <value>
                    <fullName>DC_Easton_Village</fullName>
                </value>
                <value>
                    <fullName>DC_Heritage_Shores</fullName>
                </value>
                <value>
                    <fullName>DC_Liberty</fullName>
                </value>
                <value>
                    <fullName>DC_Mayfair</fullName>
                </value>
                <value>
                    <fullName>DC_Oakview_Village</fullName>
                </value>
                <value>
                    <fullName>DC_Potomac_Shores</fullName>
                </value>
                <value>
                    <fullName>DC_Ridgeview</fullName>
                </value>
                <value>
                    <fullName>DC_Bluffs_at_Sleeter_Lake</fullName>
                </value>
                <value>
                    <fullName>DC_Snowden_Bridge_Single_Family</fullName>
                </value>
                <value>
                    <fullName>DC_Snowden_Bridge_Townhomes</fullName>
                </value>
                <value>
                    <fullName>DC_Travilah_Station</fullName>
                </value>
                <value>
                    <fullName>DC_Waterford_Manor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Marketing_Community__c/fields/Sales_office__c.field-meta.xml
<CustomField>
        <fullName>Sales_office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Marketing Communities</relationshipLabel>
        <relationshipName>Marketing_Communities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Community_Text__c.field-meta.xml
<CustomField>
        <fullName>Community_Text__c</fullName>
        <description>To hold the community information from the web to lead form</description>
        <label>Community Interested In</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Visit_Date__c.field-meta.xml
<CustomField>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/Subdivision__c.object-meta.xml
<CustomObject>
    <description>NEWSTAR Sales Subdivision</description>
    <label>Subdivision</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subdivisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subdivision__c/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/BRPvalidation.cls
public with sharing class BRPvalidation
{
    public static list<Lead> LeadExists(Lead leadobj)
    {
       List<Lead> dupleadobj;
       string query= 'select Id, Name,Phone,MobilePhone,Email,Street,City,State,Community_Text__c from Lead where isconverted = false ';
       if(leadobj.email!= '')
           query=query + ' and email=\'' + leadobj.email +'\'';
       else
       {
       
           query = query + ' and lastname =\'' + leadobj.lastName + '\' and ( phone =\'' + leadobj.Phone + '\' or  MobilePhone =\'' + leadobj.mobilephone + '\' )';
       }
       system.debug(query);
       dupleadobj=Database.Query(query);
       return dupleadobj;
    }
    public static list<Interest_List__c> InterestListExists(Id LeadId,Id MarketingcommunityId)
    {
       List<Interest_List__c> Intlistleadobj=[select id, name,Interest_Status__c from Interest_list__c where lead__c=: LeadId 
       and marketing_community__c=:MarketingcommunityId order by visit_date__c desc]; 
       return Intlistleadobj;
    }
    public static list<Account> AccountExists(Lead leadobj)
    {
       // system.debug('lastname =' + leadobj.lastName + ' and marketing_division__c =' + leadobj.marketing_division__c + 'and (  phone =' + leadobj.Phone + ' or Personemail =' + leadobj.email +' or PersonMobilePhone = ' + leadobj.mobilephone +')'); 
       List<Account> accountobj=[select Id, Name,PersonEmail,PersonMobilePhone,Phone,PersonMailingAddress from Account where lastname =: leadobj.lastName 
       and (  phone =: leadobj.Phone or Personemail =: leadobj.email
       or PersonMobilePhone =: leadobj.mobilephone  )];
       return accountobj;
       
    }
    public static list<Opportunity> OpportunityExists(Id AccountId,Id MktcommId)
    {
       List<Opportunity> oppobj=[select id, name,StageName from Opportunity where accountId=: AccountId and Marketing_Community__c=: MktcommId ];
       return oppobj;
    }
    public static interest_list__c createInterestList(Interest_list__c intlstobj, Lead leadobj, Id LeadId, cobuyer__c cobuyerobj)
   {
        if (leadId==null)
            leadId=leadobj.Id;
        //for(Interest_list__c  intlst :intlstobj)
        //{
            system.debug('inside Interest list create ' + intlstobj);
            system.debug('leadId');
            intlstobj.Lead__c=leadId;
            string mrktcommunityname=Cachedcollections.myCommunityIdMap.get(intlstobj.Marketing_community__c);
            string mrktdivisionname=Cachedcollections.mySalesOfficeIdMap.get(intlstobj.Sales_office__c).split(' ')[0] + ' Interest List';
            system.debug(mrktcommunityname);
            system.debug(mrktdivisionname);
            intlstobj.Name= leadobj.FirstName + ' ' + leadobj.LastName + ' - ' + mrktcommunityname;
           
            intlstobj.recordTypeId=Schema.SObjectType.Interest_list__c.getRecordTypeInfosByName().get(mrktdivisionname).getRecordTypeId();
            intlstobj.stage__c='New';
            if(leadobj.Is_Hubspot_lead__c==true)
            {
                //system.debug('mktg comm name4: ' + intlstobj.Marketing_Community__r.Name);
                //system.debug('mktg comm name5: ' + mrktcommunityname);
                string commtname=Cachedcollections.myCommunityMap.get(mrktcommunityname).Assigned_Queue__c.replace('_', ' ');
//                string commtname=Cachedcollections.myCommunityMap.get(intlstobj.marketing_community__r.Name).Assigned_Queue__c.replace('_', ' ');
                //system.debug(commtname);
                intlstobj.ownerId= getInterestListOwnerId(commtname);
            }
            
            
       // }
        insert intLstobj;
        if(cobuyerobj!=null)
        {
                cobuyerobj.recordtypeId=Schema.SObjectType.Cobuyer__c.getRecordTypeInfosByName().get('Interest List').getRecordTypeId();
                cobuyerobj.Interest_List__c= intLstobj.Id;
                insert  cobuyerobj; 
        }
        return intlstObj;
   }
   public static Opportunity createOpportunity(interest_list__c intlstobj, lead leadobj, Id AcctId, cobuyer__c cobuyerobj)
   {
            Opportunity oppobj=new opportunity();
            oppobj.Name= leadObj.FirstName + ' ' + leadObj.LastName + ' - ' + Cachedcollections.mysubdivisionIdMap.get(intLstobj.subdivision__c);
            oppobj.accountid=AcctId;
            oppobj.Marketing_Community__c  = intLstobj.Marketing_Community__c;
            oppobj.Sales_office__c=intLstobj.Sales_office__c;
            oppobj.Subdivision__c   =intLstobj.Subdivision__c ;
            oppobj.Visit_Date__c = intLstobj.Visit_Date__c;
            if(intlstobj.stage__c=='New')
                oppobj.StageName='Prospecting';
            else if(intlstobj.stage__c=='Lead Lost')
                oppobj.StageName='Closed Lost';
            else if(intlstobj.stage__c=='Working')
                oppobj.StageName='Engagement';
            oppobj.closeDate=date.today().addDays(60); 
            oppobj.Scenario_Name__c='Default Scenario';
            insert oppobj;
            if(cobuyerobj!=null)
            {
                cobuyerobj.recordtypeId=Schema.SObjectType.Cobuyer__c.getRecordTypeInfosByName().get('Opportunity').getRecordTypeId();
                cobuyerobj.Interest_List__c= oppObj.Id;
                insert  cobuyerobj; 
            }
            return oppobj;
   }
   private static Id getInterestListOwnerId(string communityname)
   {
       QueueSObject QueueID = [Select Queue.Id, Queue.Name, Queue.Type from QueueSObject WHERE Queue.Type ='Queue' AND Queue.Name =: communityname Limit 1];
       return QueueID.Queue.Id; 

   }
   public void genericInterestcreation( sobject s,string actiontype,string val, string activelistfieldname, string historylistfieldname  )
   {
      list<string> lstcommunity=new list<string>();
      list<string> lstcommunityHist=new list<string>();
      string activevalue=(string)s.get(activelistfieldname);
      string historyvalue=(string)s.get(historylistfieldname);
      system.debug(activevalue);
      system.debug(historyvalue);
      if(activevalue!=null)
          lstcommunity = activevalue.split('\n');
      if(historyvalue!=null)
          lstcommunityHist = historyvalue.split('\n');
      if(lstcommunity.size()>0)
          {
              if(actiontype=='Insert')
                   {
                       if(lstCommunity.contains(val)==false)
                          s.put(activelistfieldname, activevalue + '\n' + val);
                   }
              else if(actiontype=='Delete')
                   {
                       lstcommunity.remove(lstCommunity.indexOf(val));
                       string newlist='';
                       for(integer i=0;i<lstcommunity.size();i++)
                       newlist = newlist + '\n' + lstcommunity[i];
                       s.put(activelistfieldname,newlist);                                 
                   }

           }
       else
           {
               if(actiontype=='Insert')
                   s.put(activelistfieldname, val);

           }
                          
       if(lstcommunityHist.size()>0)
           {
               if(actiontype=='Insert')
                   {
                        if(lstcommunityHist.contains(val)==false)
                             s.put(historylistfieldname  , historyvalue + '\n' + val);
                   }
           }
        else
           {
               if(actiontype=='Insert')
                         s.put(historylistfieldname, val);

           }
      
   }
   public static string getsalesofficename(sobject s)
    {
        string sname=(string) s.get('sales_office_mapping__c');
        BRPSalesSettings__c soffname= BRPSalesSettings__c.getInstance(sname.split(' ')[0]);
        return soffname.Sales_Office_Name__c ;
    }
    public static string getsalesofficename(string sname)
    {
        //string sname=(string) s.get('sales_office_mapping__c');
        BRPSalesSettings__c soffname= BRPSalesSettings__c.getInstance(sname.split(' ')[0]);
        return soffname.Sales_Office_Name__c ;
    }
}