unpackaged/main/default/objects/Account/fields/Sales_Office_mapping__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office_mapping__c</fullName>
        <label>Sales Office mapping</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/BeBack__c/BeBack__c.object-meta.xml
<CustomObject>
    <label>Prospect Note</label>
    <nameField>
        <label>Prospect Note</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospect Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BeBack__c/fields/Is_Be_Back__c.field-meta.xml
<CustomField>
        <fullName>Is_Be_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Be Back</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/BeBack__c/fields/Notes__c.field-meta.xml
<CustomField>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </CustomField>

unpackaged/main/default/objects/BeBack__c/fields/Opportunity__c.field-meta.xml
<CustomField>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Prospect Notes</relationshipLabel>
        <relationshipName>Prospect_Notes</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/BeBack__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
        <fullName>Visit_Date__c</fullName>
        <label>Entry Date</label>
        <required>true</required>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Default.recordType-meta.xml
<RecordType>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </RecordType>

unpackaged/main/default/objects/HS_Create_Lead__e/HS_Create_Lead__e.object-meta.xml
<CustomObject>
    <label>HS Create Lead</label>
    <pluralLabel>HS create leads</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/HS_Create_Lead__e/fields/recordid__c.field-meta.xml
<CustomField>
        <fullName>recordid__c</fullName>
        <label>recordid</label>
        <length>18</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Converted_From_Lead__c.field-meta.xml
<CustomField>
        <fullName>Converted_From_Lead__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Converted From Lead</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Realtor__c.field-meta.xml
<CustomField>
        <fullName>Realtor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Are You a Realtor?</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Sales_office_mapping__c.field-meta.xml
<CustomField>
        <fullName>Sales_office_mapping__c</fullName>
        <label>Sales office mapping</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Marketing_Community__c/Marketing_Community__c.object-meta.xml
<CustomObject>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Marketing_Community__c/fields/Sales_office__c.field-meta.xml
<CustomField>
        <fullName>Sales_office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Marketing Communities</relationshipLabel>
        <relationshipName>Marketing_Communities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Converted_From_Lead__c.field-meta.xml
<CustomField>
        <fullName>Converted_From_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted From Lead</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Real_Estate_Agent__c.field-meta.xml
<CustomField>
        <fullName>Real_Estate_Agent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Real Estate Agent</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Select a valid real estate agent</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Real Estate Agent</value>
            </filterItems>
            <infoMessage>Select a real estate agent representing the customer for this deal.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Scenario_Name__c.field-meta.xml
<CustomField>
        <fullName>Scenario_Name__c</fullName>
        <label>Scenario Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Subdivision must belong to the selected sales office and the selected marketing community.</errorMessage>
            <filterItems>
                <field>Subdivision__c.Sales_Office__c</field>
                <operation>equals</operation>
                <valueField>$Source.Sales_Office__c</valueField>
            </filterItems>
            <filterItems>
                <field>Subdivision__c.Marketing_Community__c</field>
                <operation>equals</operation>
                <valueField>$Source.Marketing_Community__c</valueField>
            </filterItems>
            <infoMessage>Select a subdivision</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Visit_Date__c.field-meta.xml
<CustomField>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Sales_Office__c/Sales_Office__c.object-meta.xml
<CustomObject>
    <description>NEWSTAR Sales Office</description>
    <label>Sales Office</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subdivision__c/Subdivision__c.object-meta.xml
<CustomObject>
    <description>NEWSTAR Sales Subdivision</description>
    <label>Subdivision</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subdivisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subdivision__c/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/LeadandAccountTriggerHandler.cls
public with sharing class LeadandAccountTriggerHandler
{
    public  void leadconvert(list<Lead> lstlead)
    {   
        for(Lead ld:lstLead)
        {
            if(ld.isconverted==false)
            {
                Database.LeadConvertResult lcr=convertLead(ld.Id);
                if(lcr.isSuccess())
                {
                    Id AccountId=lcr.getAccountId();
                    Account acc=[select Id, recordtypeId,FirstName,LastName,sales_office_mapping__c from  Account where Id=: AccountId];
                    acc.recordtypeId=account.SObjectType.getDescribe().getRecordTypeInfosByName().get('Customer').getRecordTypeId();
                    update acc;
                    sobject s=ld;
                    string nameval=BRPValidation.getsalesofficename(acc);
                    ValidateExistingopportunities(acc);
                    HS_Create_Lead__e event=new HS_Create_Lead__e(recordid__c=AccountId);
                    Eventbus.publish(event);
                    //return AccountId;
                }
            }
        }
        
    }
    private Database.LeadConvertResult convertLead(Id leadId)
    {
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        
            Database.LeadConvert lc = new Database.LeadConvert();
            lc.setLeadId(leadId);
            lc.setDoNotCreateOpportunity(true);
            lc.setConvertedStatus(convertStatus.MasterLabel);
            system.debug('Before lead convert');
            try{
                system.debug('Inside Lead convert');
                return Database.convertLead(lc);
            }
            catch (Exception ex) {
                System.debug('@@@@ - convert error: ' + ex.getMessage());
           // ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error,string.valueof(ex));
            //ApexPages.addMessage(myMsg);
               // throw new AuraHandledException('Error Exception happend'+ex.getMessage());           
            return null;
            }
    }
    
    private void createOpportunities(account acct,string mktcomm)
    {
        List<Opportunity> lstOpp=new list<Opportunity>();
        Set<Id> setIntlst= new Set<Id>();

        integer index=0;
        list<contact> lstContact= [select Id from Contact where accountid=: acct.Id];
        try
        {
               Opportunity opp=new Opportunity();
               opp.accountId=acct.Id;
               opp.name=acct.Firstname + ' ' + acct.LastName + ' - ' + mktcomm;
               Marketing_community__c mktcommobj=Cachedcollections.myCommunityMap.get(mktcomm);
               opp.marketing_community__c=mktcommobj.Id;
               //opp.LeadSource=ld.leadsource;
               opp.StageName='Prospecting';//intlst.stage__c;
               //if (intLst.lead_source__c!= '')
               //    opp.LeadSource=intLst.lead_source__c;
               opp.closeDate=date.today().addDays(60); /* Look into target close date in newstar*/
               opp.Converted_From_Lead__c=true;
               //if (intLst.Realtor__c!= '')
               //    opp.Real_Estate_Agent__c=intLst.Realtor__c;
               opp.Sales_Office__c=mktcommobj.sales_office__c;
               opp.Scenario_Name__c='Default Scenario';
               lstopp.add(opp);
               insert lstOpp;
       list<OpportunityContactRole> lstoppconrole=new list<OpportunityContactRole>();
        for(Opportunity o : lstOpp)
        {
            OpportunityContactRole ocr = new OpportunityContactRole();
            ocr.OpportunityId = o.Id;
            ocr.ContactId = lstcontact[0].Id;
            ocr.Role = 'Primary Buyer';
            lstoppconrole.add(ocr);
        }
        insert lstoppconrole;
        }
        catch(exception ex)
        {

        }
        
    }
  
  public void ValidateExistingopportunities(account acc)
  {
       
       boolean OppinProgress=true;
       Id OppId;
       sobject s=acc;
       string nameval=BRPValidation.getsalesofficename(s);
       Id mktcommId= cachedcollections.myCommunityMap.get((string) s.get('Community_Picklist_'+ nameval +'__pc')).Id;
       List<Opportunity> opplistexist=BRPvalidation.OpportunityExists(acc.Id,mktcommId);
       if(opplistexist.size()>0)
       {
            for(Opportunity opplst : opplistexist)
            {
               if(opplst.StageName =='Closed Home' || opplst.StageName =='Cancelled')
                 {
                    OppinProgress=false;
                 }
                 else
                 {
                    OppId=opplst.Id;
                 }
            }
            if(!OppinProgress)
              {
                  createOpportunities(acc,(string) s.get('Community_Picklist_'+ nameval +'__pc'));
              }
              else
              {
                        /*beback__c bebacknote=new beback__c();
                        bebacknote.Is_Be_Back__c=true;
                        bebacknote.Opportunity__c=OppId;
                        bebacknote.visit_date__c=date.today();
                        bebacknote.notes__c='customer returned for more information';
                        //bebacknote.name='Note for ' + Cachedcollections.mysubdivisionIdMap.get(intLstobj.subdivision__c);
                        insert bebacknote;*/
              }
        }
        else
        {
            createOpportunities(acc,(string) s.get('Community_Picklist_'+ nameval +'__pc'));
 
        }
  }
}