unpackaged/main/default/objects/Contact/fields/Age_Group__c.field-meta.xml
<CustomField>
        <fullName>Age_Group__c</fullName>
        <label>Age Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Age_Group</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Contact/fields/Are_you_transferring_to_the_area__c.field-meta.xml
<CustomField>
        <fullName>Are_you_transferring_to_the_area__c</fullName>
        <label>Are you transferring to the area?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Contact/fields/Bathrooms__c.field-meta.xml
<CustomField>
        <fullName>Bathrooms__c</fullName>
        <label>Bathrooms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bathrooms</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Contact/fields/Bedrooms__c.field-meta.xml
<CustomField>
        <fullName>Bedrooms__c</fullName>
        <label>Bedrooms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bedrooms</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Contact/fields/Community_Picklist_Wsh__c.field-meta.xml
<CustomField>
        <fullName>Community_Picklist_Wsh__c</fullName>
        <label>Contact Community Picklist Wsh</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Age_Group__c.field-meta.xml
<CustomField>
        <fullName>Age_Group__c</fullName>
        <label>Age Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>18 - 24</fullName>
                </value>
                <value>
                    <fullName>25 - 34</fullName>
                </value>
                <value>
                    <fullName>35 - 44</fullName>
                </value>
                <value>
                    <fullName>45 - 54</fullName>
                </value>
                <value>
                    <fullName>55 - 64</fullName>
                </value>
                <value>
                    <fullName>65+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Are_you_transferring_to_the_area__c.field-meta.xml
<CustomField>
        <fullName>Are_you_transferring_to_the_area__c</fullName>
        <inlineHelpText>If transferring to the area, enter transfer date.</inlineHelpText>
        <label>Are you transferring to the area?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Area_of_Interest__c.field-meta.xml
<CustomField>
        <fullName>Area_of_Interest__c</fullName>
        <inlineHelpText>Select all areas of interest</inlineHelpText>
        <label>Area of Interest</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cedar Park / Leander</fullName>
                </value>
                <value>
                    <fullName>Central &amp; East Austin</fullName>
                </value>
                <value>
                    <fullName>Dripping Springs</fullName>
                </value>
                <value>
                    <fullName>Georgetown / Liberty Hill</fullName>
                </value>
                <value>
                    <fullName>Lakeway / Bee Cave</fullName>
                </value>
                <value>
                    <fullName>San Marcos</fullName>
                </value>
                <value>
                    <fullName>No Preference</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Bathrooms__c.field-meta.xml
<CustomField>
        <fullName>Bathrooms__c</fullName>
        <label>Bathrooms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>2.5</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>3.5</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>4+</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Bedrooms__c.field-meta.xml
<CustomField>
        <fullName>Bedrooms__c</fullName>
        <label>Bedrooms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>5+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Community_Picklist_Wsh__c.field-meta.xml
<CustomField>
        <fullName>Community_Picklist_Wsh__c</fullName>
        <label>Community Picklist Wsh</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Do_you_currently_own_or_rent__c.field-meta.xml
<CustomField>
        <fullName>Do_you_currently_own_or_rent__c</fullName>
        <label>Do you currently own or rent?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Own</fullName>
                </value>
                <value>
                    <fullName>Rent</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Household_Income__c.field-meta.xml
<CustomField>
        <fullName>Household_Income__c</fullName>
        <label>Household Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Up to $39,000</fullName>
                </value>
                <value>
                    <fullName>$40,000 - $99,000</fullName>
                </value>
                <value>
                    <fullName>$100,000 - $149,000</fullName>
                </value>
                <value>
                    <fullName>$150,000 - $199,000</fullName>
                </value>
                <value>
                    <fullName>$200,000 - $299,000</fullName>
                </value>
                <value>
                    <fullName>$300,000 - $399,000</fullName>
                </value>
                <value>
                    <fullName>$400,000+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/How_long_have_you_been_house_hunting__c.field-meta.xml
<CustomField>
        <fullName>How_long_have_you_been_house_hunting__c</fullName>
        <label>How long have you been house hunting?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Less than 1 Month</fullName>
                </value>
                <value>
                    <fullName>1-3 Months</fullName>
                </value>
                <value>
                    <fullName>3-6 Months</fullName>
                </value>
                <value>
                    <fullName>6+ Months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Lead_Source_Detail__c.field-meta.xml
<CustomField>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/MaritalStatus__c.field-meta.xml
<CustomField>
        <fullName>MaritalStatus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MaritalStatus</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Number_of_Children_in_Home__c.field-meta.xml
<CustomField>
        <fullName>Number_of_Children_in_Home__c</fullName>
        <label>Number of Children in Home</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Realtor__c.field-meta.xml
<CustomField>
        <fullName>Realtor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Are You a Realtor?</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Sales_office_mapping__c.field-meta.xml
<CustomField>
        <fullName>Sales_office_mapping__c</fullName>
        <label>Sales office mapping</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Transferring_to_area_date__c.field-meta.xml
<CustomField>
        <fullName>Transferring_to_area_date__c</fullName>
        <inlineHelpText>If lead is transferring to the area, enter date they expect to transfer.</inlineHelpText>
        <label>Transferring to area date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/TX_Timeframe_to_purchase__c.field-meta.xml
<CustomField>
        <fullName>TX_Timeframe_to_purchase__c</fullName>
        <label>Timeframe to purchase</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>30 Day</fullName>
                </value>
                <value>
                    <fullName>1-3 Month</fullName>
                </value>
                <value>
                    <fullName>3-6 Month</fullName>
                </value>
                <value>
                    <fullName>0-6 Months</fullName>
                </value>
                <value>
                    <fullName>6-12 Months</fullName>
                </value>
                <value>
                    <fullName>1 Year</fullName>
                </value>
                <value>
                    <fullName>1-2 Years</fullName>
                </value>
                <value>
                    <fullName>2+ Years</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Visit_Brookfield_website_during_search__c.field-meta.xml
<CustomField>
        <fullName>Visit_Brookfield_website_during_search__c</fullName>
        <label>Visit Brookfield website during search?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/What_is_your_price_range__c.field-meta.xml
<CustomField>
        <fullName>What_is_your_price_range__c</fullName>
        <inlineHelpText>Legacy TX Lead field for Marketing purposes</inlineHelpText>
        <label>What is your price range?</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>$100,000 - $149,999</fullName>
                </value>
                <value>
                    <fullName>$150,000 - $199,999</fullName>
                </value>
                <value>
                    <fullName>Under $200,000</fullName>
                </value>
                <value>
                    <fullName>$200,000 - $249,000</fullName>
                </value>
                <value>
                    <fullName>$250,000 - $299,999</fullName>
                </value>
                <value>
                    <fullName>$300,000 - $349,999</fullName>
                </value>
                <value>
                    <fullName>$350,000 - $399,999</fullName>
                </value>
                <value>
                    <fullName>$400,000 - $500,000</fullName>
                </value>
                <value>
                    <fullName>Over $500,000</fullName>
                </value>
                <value>
                    <fullName>$400,000 - $499,999</fullName>
                </value>
                <value>
                    <fullName>$500,000 - $700,000</fullName>
                </value>
                <value>
                    <fullName>Over $700,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/globalValueSets/Age_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>18 - 24</fullName>
    </customValue>
    <customValue>
        <fullName>25 - 34</fullName>
    </customValue>
    <customValue>
        <fullName>35 - 44</fullName>
    </customValue>
    <customValue>
        <fullName>45 - 54</fullName>
    </customValue>
    <customValue>
        <fullName>55 - 64</fullName>
    </customValue>
    <customValue>
        <fullName>65+</fullName>
    </customValue>
    <masterLabel>Age Group</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Hubspotcreationcalls.cls
public class Hubspotcreationcalls
{
   public void createcontactonHS(lead leadobj)
   {
        string pc=createHsJson(leadobj);
        //string prospectJSON = JSON.serialize(pc);
        string apikey='8b365b09-a3b2-423d-b401-c468c9f89e2c';
        string url='https://api.hubapi.com/contacts/v1/contact/?hapikey=' + apikey;
        //string url='https://forms.hubspot.com/uploads/form/v2/6035427/76cb4fcc-1514-444a-b627-5714574482b0';
        system.debug(pc);
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        //req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        
        req.setBody(pc); 
        Http http = new Http(); 
          try
            {
                HTTPResponse res = http.send(req);
                Integer retCode = res.getStatusCode();
                String retMsg = res.getStatus();
                if(retcode==500)
                {
                }
            }
            catch(exception ex)
            {
            }
    }
   public static string createHsJson(lead leadobj) 
   {
       JSONGenerator pc= JSON.createGenerator(true);
       pc.writeStartObject();
       pc.writeFieldName('properties');
       pc.writeStartArray();
        // First name
             pc.writestartObject();
             pc.writeObjectField('property','firstname');
             pc.writeObjectField('value',leadobj.firstname);
             pc.writeEndObject();
              // Last name
             pc.writestartObject();
             pc.writeObjectField('property','lastname');
             pc.writeObjectField('value',leadobj.lastname);
             pc.writeEndObject();
              // email
             pc.writestartObject();
             pc.writeObjectField('property','email');
             pc.writeObjectField('value',leadobj.email);
             pc.writeEndObject();
             
              // community interested
             pc.writestartObject();
             pc.writeObjectField('property','community_picklist_wash');
             pc.writeObjectField('value',leadobj.Community_Picklist_Wsh__c);
             pc.writeEndObject();
             
             if(leadobj.LeadSource!='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','leadsource');
              pc.writeObjectField('value',leadobj.leadsource);
              pc.writeEndObject();
             }
             if(leadobj.Lead_Source_Detail__c!='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','lead_source_detail__c');
              pc.writeObjectField('value',leadobj.Lead_Source_Detail__c);
              pc.writeEndObject();
             }
             if(leadobj.area_of_interest__c!='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','area_of_interest__c');
              pc.writeObjectField('value',leadobj.area_of_interest__c);
              pc.writeEndObject();
             }
             //if(leadobj.realtor__c!='')
            // {
              pc.writestartObject();
              pc.writeObjectField('property','realtor__c');
              pc.writeObjectField('value',leadobj.realtor__c);
              pc.writeEndObject();
            // }
             if(leadobj.age_group__c !='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','age_group__c');
              pc.writeObjectField('value',leadobj.age_group__c );
              pc.writeEndObject();
             }
            // if(leadobj.maritalstatus__c !='')
            // {
              pc.writestartObject();
              pc.writeObjectField('property','maritalstatus__c');
              pc.writeObjectField('value',leadobj.maritalstatus__c );
              pc.writeEndObject();
            // }
             if(leadobj.do_you_currently_own_or_rent__c !='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','do_you_currently_own_or_rent__c');
              pc.writeObjectField('value',leadobj.do_you_currently_own_or_rent__c );
              pc.writeEndObject();
             }
             if(leadobj.are_you_transferring_to_the_area__c !='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','are_you_transferring_to_the_area__c');
              pc.writeObjectField('value',leadobj.are_you_transferring_to_the_area__c );
              pc.writeEndObject();
             }
             if(leadobj.transferring_to_area_date__c !=null)
             {
              pc.writestartObject();
              pc.writeObjectField('property','transferring_to_area_date__c');
              pc.writeObjectField('value',leadobj.transferring_to_area_date__c);
              pc.writeEndObject();
             }
             if(leadobj.how_long_have_you_been_house_hunting__c  !='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','how_long_have_you_been_house_hunting__c');
              pc.writeObjectField('value',leadobj.how_long_have_you_been_house_hunting__c);
              pc.writeEndObject();
             }
             if(leadobj.visit_brookfield_website_during_search__c !='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','visit_brookfield_website_during_search__c');
              pc.writeObjectField('value',leadobj.visit_brookfield_website_during_search__c);
              pc.writeEndObject();
             }
             if(leadobj.household_income__c !='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','household_income__c');
              pc.writeObjectField('value',leadobj.household_income__c);
              pc.writeEndObject();
             }
             if(leadobj.tx_timeframe_to_purchase__c !='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','tx_timeframe_to_purchase__c');
              pc.writeObjectField('value',leadobj.tx_timeframe_to_purchase__c);
              pc.writeEndObject();
             }
             if(leadobj.number_of_children_in_home__c!='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','number_of_children_in_home__c');
              pc.writeObjectField('value',leadobj.number_of_children_in_home__c);
              pc.writeEndObject();
             }
             if(leadobj.what_is_your_price_range__c !='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','what_is_your_price_range__c');
              pc.writeObjectField('value',leadobj.what_is_your_price_range__c );
              pc.writeEndObject();
             }
             if(leadobj.bedrooms__c !='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','bedrooms__c');
              pc.writeObjectField('value',leadobj.bedrooms__c );
              pc.writeEndObject();
             }
             if(leadobj.bathrooms__c !='')
             {
              pc.writestartObject();
              pc.writeObjectField('property','bathrooms__c');
              pc.writeObjectField('value',leadobj.bathrooms__c);
              pc.writeEndObject();
             }
              
              string salesoffice= quickLeadCreate.getSalesOffices()[0].Sales_Office__r.Name;
              pc.writestartObject();
              pc.writeObjectField('property','sales_office_mapping__c');
              pc.writeObjectField('value',salesoffice);
              pc.writeEndObject();
     
            
         //}
       pc.writeEndarray();
       pc.writeEndObject();
       string body= pc.getAsString();
       system.debug('Json for hs' + body);
       return body;
   }      
   public static void createHsformdata(lead leadobj) 
   {
       string formdata='';
       
       formdata=formdata +'firstname=' + EncodingUtil.urlEncode(leadobj.firstname,'utf-8');
       formdata=formdata +'&lastname=' + EncodingUtil.urlEncode(leadobj.lastname,'utf-8');
       formdata=formdata +'&email=' + EncodingUtil.urlEncode(leadobj.email,'utf-8');
       formdata=formdata +'&community_picklist_wash=' + EncodingUtil.urlEncode(leadobj.Community_Picklist_Wsh__c,'utf-8');
       formdata=formdata +'&realtor__c=' + leadobj.realtor__c;
       formdata=formdata +'&maritalstatus__c=' + leadobj.maritalstatus__c;
       string salesoffice= quickLeadCreate.getSalesOffices()[0].Sales_Office__r.Name;
       formdata=formdata +'&sales_office_mapping__c=' + EncodingUtil.urlEncode(salesoffice,'utf-8');
       
       if(leadobj.LeadSource!='')
           formdata=formdata +'&leadsource=' + EncodingUtil.urlEncode(leadobj.leadsource,'utf-8');
       if(leadobj.lead_source_detail__c!='')
           formdata=formdata +'&lead_source_detail__c=' + EncodingUtil.urlEncode(leadobj.lead_source_detail__c,'utf-8');
       if(leadobj.area_of_interest__c!='')
           formdata=formdata +'&area_of_interest__c=' + EncodingUtil.urlEncode(leadobj.area_of_interest__c,'utf-8');
       
       if(leadobj.age_group__c!='')
           formdata=formdata +'&age_group__c=' + EncodingUtil.urlEncode(leadobj.age_group__c,'utf-8');

       if(leadobj.do_you_currently_own_or_rent__c!='')
           formdata=formdata +'&do_you_currently_own_or_rent__c=' + EncodingUtil.urlEncode(leadobj.do_you_currently_own_or_rent__c,'utf-8');
       if(leadobj.are_you_transferring_to_the_area__c!='')
           formdata=formdata +'&are_you_transferring_to_the_area__c=' + EncodingUtil.urlEncode(leadobj.are_you_transferring_to_the_area__c,'utf-8');
        formdata=formdata +'&transferring_to_area_date__c=' + leadobj.transferring_to_area_date__c;
       if(leadobj.how_long_have_you_been_house_hunting__c!='')
           formdata=formdata +'&how_long_have_you_been_house_hunting__c=' + EncodingUtil.urlEncode(leadobj.how_long_have_you_been_house_hunting__c,'utf-8');
       if(leadobj.visit_brookfield_website_during_search__c!='')
           formdata=formdata +'&visit_brookfield_website_during_search__c=' + EncodingUtil.urlEncode(leadobj.visit_brookfield_website_during_search__c,'utf-8');
       if(leadobj.household_income__c!='')
           formdata=formdata +'&household_income__c=' + EncodingUtil.urlEncode(leadobj.household_income__c,'utf-8');
       if(leadobj.what_is_your_price_range__c !='')
           formdata=formdata +'&what_is_your_price_range__c =' + EncodingUtil.urlEncode(leadobj.what_is_your_price_range__c ,'utf-8');
       if(leadobj.bedrooms__c!='')
           formdata=formdata +'&bedrooms__c=' + EncodingUtil.urlEncode(leadobj.bedrooms__c,'utf-8');
       if(leadobj.bathrooms__c!='')
           formdata=formdata +'&bathrooms__c=' + EncodingUtil.urlEncode(leadobj.bathrooms__c,'utf-8');
       
       
       
       JSONGenerator pc= JSON.createGenerator(true);
       pc.writeStartObject();
       pc.writeStringField('hutk','76cb4fcc-1514-444a-b627-5714574482b0');
       pc.writeEndObject();
       string body= pc.getAsString();
       formdata=formdata + '&hs_context=' + body;
       system.debug(formdata);
       string url='https://forms.hubspot.com/uploads/form/v2/6035427/76cb4fcc-1514-444a-b627-5714574482b0';
        system.debug(pc);
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('POST');
        //req.setHeader('Content-Type', 'application/json');
        req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        
        req.setBody(formdata); 
        Http http = new Http(); 
          try
            {

            HTTPResponse res = http.send(req);
            Integer retCode = res.getStatusCode();
            String retMsg = res.getStatus();
            }
            catch(exception ex)
            {
            }
   }      
}