unpackaged/main/default/objects/BeBack__c/BeBack__c.object-meta.xml
<CustomObject>
    <label>Prospect Note</label>
    <nameField>
        <label>Prospect Note</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospect Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BeBack__c/fields/Community_of_Interest__c.field-meta.xml
<CustomField>
        <fullName>Community_of_Interest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interestested community</label>
        <referenceTo>Interest_List__c</referenceTo>
        <relationshipLabel>Prospect Notes</relationshipLabel>
        <relationshipName>BeBack</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/BeBack__c/fields/Is_Be_Back__c.field-meta.xml
<CustomField>
        <fullName>Is_Be_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Be Back</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/BeBack__c/fields/Notes__c.field-meta.xml
<CustomField>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </CustomField>

unpackaged/main/default/objects/BeBack__c/fields/Opportunity__c.field-meta.xml
<CustomField>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Prospect Notes</relationshipLabel>
        <relationshipName>Prospect_Notes</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/BeBack__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
        <fullName>Visit_Date__c</fullName>
        <label>Entry Date</label>
        <required>true</required>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/Interest_List__c.object-meta.xml
<CustomObject>
    <label>Interest List</label>
    <nameField>
        <label>Interest List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Interest_List__c/fields/Lead__c.field-meta.xml
<CustomField>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Marketing_Community__c/Marketing_Community__c.object-meta.xml
<CustomObject>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Opportunity/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Visit_Date__c.field-meta.xml
<CustomField>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/classes/Notessummary.cls
public inherited sharing class Notessummary
{
    public lead leadObj{get; set;} 
    public account acctobj{get;set;}
    public Interest_List__c intLstobj{get; set;}
    public string notes{get; set;}
    public Notessummary(ApexPages.StandardController controller) 
    {
      this.notes='';
      String type = controller.getRecord().getSObjectType().getDescribe().getName();
      if (type=='Lead')
          this.leadobj = (Lead)Controller.getRecord();
      else
          this.acctobj = (Account)Controller.getRecord();
      Getnotes(type);
    }
    private void Getnotes(string type)
    {
        list<beBack__c> prospectnotes;
        if(type=='Lead')
            prospectnotes=[select notes__c,visit_date__c,name, is_be_back__c, Community_of_Interest__c,Community_of_Interest__r.marketing_community__r.Name,Owner.Name   from beback__c where  Community_of_Interest__c in
            (select id from interest_list__c where lead__c =: leadobj.Id) order by visit_date__c desc];
        else
            prospectnotes=[select notes__c,visit_date__c,name, is_be_back__c, opportunity__c,opportunity__r.marketing_community__r.Name,Owner.Name  from beback__c where  opportunity__c in
            (select id from opportunity where accountid =: acctobj.Id) order by visit_date__c desc];
        for(beback__c n: prospectnotes)
        {
            //system.debug(n.Community_of_Interest__r.marketing_community__r.Name);
            Date dt=n.Visit_date__c;
            string beback=': Is Be back';
            if(n.is_be_back__c==true)
                 
                 if(type=='Lead')
                    this.notes=this.notes+ dt.day() + '-'+ dt.Month() + '-' + dt.year() + beback +'</br>'  + 'Project: ' 
                    + n.Community_of_Interest__r.marketing_community__r.Name +'</br>'
                    + n.Owner.Name + ': ' + n.notes__c + '</p>';
                 else
                      this.notes=this.notes+ dt.day() + '-'+ dt.Month() + '-' + dt.year() + beback +'</br>' + 'Project: '
                    + n.opportunity__r.marketing_community__r.Name +'</br>'
                    + n.Owner.Name + ': ' + n.notes__c + '</p>';
                 
            else
                 
                 if(type=='Lead')
                    this.notes=this.notes+ dt.day() + '-'+ dt.Month() + '-' +dt.year() +'</br>' 
                    + 'Project: ' + n.Community_of_Interest__r.marketing_community__r.Name +'</br>'
                    + n.Owner.Name + ': ' + n.notes__c + '</p>';
                 else
                     this.notes=this.notes+ dt.day() + '-'+ dt.Month() + '-' +dt.year() +'</br>' 
                     + 'Project: ' + n.opportunity__r.marketing_community__r.Name +'</br>'
                     + n.Owner.Name + ': ' + n.notes__c + '</p>';
                 
           
        }

    }
}