unpackaged/main/default/objects/BeBack__c/BeBack__c.object-meta.xml
<CustomObject>
    <label>Prospect Note</label>
    <nameField>
        <label>Prospect Note</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospect Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BeBack__c/fields/Community_of_Interest__c.field-meta.xml
<CustomField>
        <fullName>Community_of_Interest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interestested community</label>
        <referenceTo>Interest_List__c</referenceTo>
        <relationshipLabel>Prospect Notes</relationshipLabel>
        <relationshipName>BeBack</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/BeBack__c/fields/Is_Be_Back__c.field-meta.xml
<CustomField>
        <fullName>Is_Be_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Be Back</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/BeBack__c/fields/Notes__c.field-meta.xml
<CustomField>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </CustomField>

unpackaged/main/default/objects/BeBack__c/fields/Opportunity__c.field-meta.xml
<CustomField>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Prospect Notes</relationshipLabel>
        <relationshipName>Prospect_Notes</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/BeBack__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
        <fullName>Visit_Date__c</fullName>
        <label>Entry Date</label>
        <required>true</required>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Cobuyer__c/Cobuyer__c.object-meta.xml
<CustomObject>
    <label>Cobuyer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cobuyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Cobuyer__c/fields/Interest_List__c.field-meta.xml
<CustomField>
        <fullName>Interest_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interest List</label>
        <referenceTo>Interest_List__c</referenceTo>
        <relationshipLabel>Cobuyers</relationshipLabel>
        <relationshipName>Cobuyers</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Cobuyer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cobuyers</relationshipLabel>
        <relationshipName>Cobuyers</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Cobuyer__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </RecordType>

unpackaged/main/default/objects/Interest_List__c/Interest_List__c.object-meta.xml
<CustomObject>
    <label>Interest List</label>
    <nameField>
        <label>Interest List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Interest_List__c/fields/Interest_Status__c.field-meta.xml
<CustomField>
        <fullName>Interest_Status__c</fullName>
        <label>Interest Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Stage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Responded</fullName>
                </value>
                <value>
                    <fullName>Responded Nurture</fullName>
                </value>
                <value>
                    <fullName>Unattended Tour</fullName>
                </value>
                <value>
                    <fullName>Confirmed Appointment</fullName>
                </value>
                <value>
                    <fullName>Missed Appointment</fullName>
                </value>
                <value>
                    <fullName>Site Visited</fullName>
                </value>
                <value>
                    <fullName>Contingent</fullName>
                </value>
                <value>
                    <fullName>Purchased</fullName>
                </value>
                <value>
                    <fullName>Prequalified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Lead/fields/Marketing_Division__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Division</label>
        <referenceTo>Marketing_Division__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Marketing_Community__c/Marketing_Community__c.object-meta.xml
<CustomObject>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Marketing_Community__c/fields/Sales_office__c.field-meta.xml
<CustomField>
        <fullName>Sales_office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Marketing Communities</relationshipLabel>
        <relationshipName>Marketing_Communities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Subdivision must belong to the selected sales office and the selected marketing community.</errorMessage>
            <filterItems>
                <field>Subdivision__c.Sales_Office__c</field>
                <operation>equals</operation>
                <valueField>$Source.Sales_Office__c</valueField>
            </filterItems>
            <filterItems>
                <field>Subdivision__c.Marketing_Community__c</field>
                <operation>equals</operation>
                <valueField>$Source.Marketing_Community__c</valueField>
            </filterItems>
            <infoMessage>Select a subdivision</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Visit_Date__c.field-meta.xml
<CustomField>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Sales_Agent__c/Sales_Agent__c.object-meta.xml
<CustomObject>
    <label>Sales Agent</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Agent__c/fields/Related_to_User__c.field-meta.xml
<CustomField>
        <fullName>Related_to_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related to User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Agents</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/SalesAgentSalesOfficeLink__c/SalesAgentSalesOfficeLink__c.object-meta.xml
<CustomObject>
    <label>Sales Agent Sales Office Relationship</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agent Sales Office Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAgentSalesOfficeLink__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/SalesAgentSalesOfficeLink__c/fields/Sales_Agent__c.field-meta.xml
<CustomField>
        <fullName>Sales_Agent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Agent</label>
        <referenceTo>Sales_Agent__c</referenceTo>
        <relationshipLabel>Sales Agent Sales Office Relationships</relationshipLabel>
        <relationshipName>Sales_Agent_Sales_Office_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/SalesAgentSalesOfficeLink__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Sales Agent Sales Office Relationships</relationshipLabel>
        <relationshipName>Sales_Agent_Sales_Office_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/Subdivision__c.object-meta.xml
<CustomObject>
    <description>NEWSTAR Sales Subdivision</description>
    <label>Subdivision</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subdivisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subdivision__c/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/quickLeadCreate.cls
public inherited sharing class quickLeadCreate
{
    
    @auraenabled
    public static string Save(Lead leadObj,Interest_list__c intLstobj, Cobuyer__c cobuyerobj, Id LeadId,Id AcctId)
    {   
          Id objid;
          try
          {
           
            if(AcctId!=null)
            {
                objid=AcctId;
                sobject s=leadobj;
                string nameval=BRPValidation.getsalesofficename(s);
                Id mktcommId= cachedcollections.myCommunityMap.get((string) s.get('Community_Picklist_'+ nameval +'__c')).Id;
                List<Opportunity> opplistexist=BRPvalidation.OpportunityExists(AcctId,mktcommId);
                boolean OppinProgress=true;
                Id OppId;
                if(opplistexist.size()>0)
                 {
                    for(Opportunity opplst : opplistexist)
                    {
                        if(opplst.StageName =='Closed Home' || opplst.StageName =='Cancelled')
                        {
                            OppinProgress=false;
                            //OppId=opplst.Id;
                        }
                        else
                        {
                            OppId=opplst.Id;
                        }
                    }
                    if(!OppinProgress)
                    {
                        BRPvalidation.createOpportunity(intLstObj,leadObj,AcctId,cobuyerObj);
                    }
                    else
                    {
                       /* beback__c bebacknote=new beback__c();
                        bebacknote.Is_Be_Back__c=true;
                        bebacknote.Opportunity__c=OppId;
                        bebacknote.visit_date__c=date.today();
                        bebacknote.notes__c='customer returned for more information';
                        bebacknote.name='Note for ' + Cachedcollections.mysubdivisionIdMap.get(intLstobj.subdivision__c);
                        insert bebacknote;*/
                    }
                 }
                 else
                 {
                     BRPvalidation.createOpportunity(intLstObj,leadObj,AcctId,cobuyerObj);
                 }
            }
            else if(LeadId ==null )
            {
                insert leadobj;
                system.debug('lead record inserted ' + leadobj );
                BRPvalidation.createInterestList(intLstObj,leadobj,leadobj.Id,cobuyerobj);
                system.debug('Interest list inserted ' + intLstObj);
                objid=leadobj.Id;
            }
            else if(LeadId !=null )
            {
                system.debug('check for duplicate InterestList');
                List<Interest_List__c> intlistexist=BRPvalidation.InterestListExists(leadId,intLstobj.marketing_community__c);
                objid=LeadId;
                boolean interestinProgress=false;
                Id intlistid;
                if(intlistexist.size()>0)
                {
                    for(Interest_list__c intlst:intlistexist)
                    {
                        if(intlst.Interest_Status__c =='Responded Nurture')
                        {
                            interestinProgress=true;
                            intlistid=intlst.Id;
                        }
                    }
                    if(!interestinProgress)
                    {
                        BRPvalidation.createInterestList(intLstObj,leadObj,leadId,cobuyerobj);
                    }
                    else
                    {
                        /*beback__c bebacknote=new beback__c();
                        bebacknote.Is_Be_Back__c=true;
                        bebacknote.Community_of_Interest__c=intlistid;
                        bebacknote.visit_date__c=date.today();
                        bebacknote.notes__c='customer returned for more information';
                        bebacknote.name='Note for ' + Cachedcollections.mysubdivisionIdMap.get(intLstobj.marketing_community__c);
                        insert bebacknote;*/
                    }
                }
                else
                {
                    BRPvalidation.createInterestList(intLstObj,leadobj,leadId,cobuyerObj);
                }
            }    
       
        }
        catch(exception ex)
        {
            system.debug(ex.getmessage());
        }
        return objId;
    }

   @auraenabled
    public static list<subdivision__c> getSubdivisions(id mktcommId, id salesOffId)
    {
       List<subdivision__c> lstsubdivisions= [select id, name from subdivision__c where Marketing_Community__c =:mktcommId and Sales_Office__c =:salesOffId ];
       return lstsubdivisions;
    }
    @auraenabled
    public static list<Marketing_community__c> getMktcommunity(id SalesOfficeId)
    {
       List<Marketing_community__c> lstMktCommunity= [select id, name from Marketing_community__c where Sales_office__c =:SalesOfficeId];
       return lstMktCommunity;
    }
    /*@auraenabled
    public static list<Marketing_Division__c> getMktDivisions()
    {
       List<Marketing_Division__c> lstmktdivisions= [select id, name from Marketing_Division__c ];
       return lstmktdivisions;
    }*/
    @auraenabled
    public static list<SalesAgentSalesOfficeLink__c> getSalesOffices()
    {
       //list<Id> lstSalesOffId=new list<id>();
       //for( SalesAgentSalesOfficeLink__c  sofficelink : 
       system.debug(UserInfo.getUserId());
       list<SalesAgentSalesOfficeLink__c> lstSalesOffice=[select Sales_Office__r.Id,Sales_Office__r.Name from SalesAgentSalesOfficeLink__c where Sales_Agent__r.Related_to_User__c=:UserInfo.getUserId() order by Is_primary__c desc ];
       //{
          /// lstSalesOffId.add(sofficelink.Id);
      // }
       //List<Sales_Office__c> lstSalesOffice= [select id, name from Sales_Office__c where Id=: lstSalesOffId];
       return lstSalesOffice;
    }
    @AuraEnabled
    public static AccountAndLead AccountAndLeadRecords(Lead leadobj)
    {
        AccountAndLead al = new AccountAndLead();
        al.a = BRPvalidation.AccountExists(leadobj) ;
        al.c = BRPvalidation.LeadExists(leadobj);
        return al;
   }
   @AuraEnabled
   public static list<Interest_List__c> getInterestLists(id leadId)
   {
       
       List<Interest_List__c> lstIntLstobj=[select Id,Marketing_Community__r.Name,Sales_Office__r.Name,Subdivision__r.name,Visit_Date__c,Interest_Status__c
       from Interest_List__c where lead__c=: leadId];
       system.debug('Interest lists:' + lstIntLstobj);
       return lstIntLstobj;
   }
   @AuraEnabled
   public static list<Opportunity> getOpportunities(id AcctId)
   {

       List<Opportunity> lstOppobj=[select Id,Marketing_Community__r.Name,Sales_Office__r.Name,Subdivision__r.name,Visit_Date__c,StageName
       from Opportunity where AccountId=: AcctId];
       system.debug('Opportunities:' + lstOppobj);
       return lstOppobj;
   }
  @Auraenabled
  public static Lead getLead(Id leadId)
  {
      return [select FirstName,LastName, Marketing_Division__c from Lead where Id=: leadId];
  }
  @AuraEnabled
    public static List<List<String>> getPicklistvalues(String objectName, String field_apinames,Boolean nullRequired){
         List<List<string>> picklists= new List<List<string>>();
        list<string> fieldnames=field_apinames.split(',');
        for (integer i =0; i<fieldnames.size(); i++)
        {
        List<String> optionlist = new List<String>();
        
        Map<String,Schema.SObjectType> gd = Schema.getGlobalDescribe(); 
        Map<String, Schema.SObjectField> field_map = gd.get(objectName.toLowerCase()).getDescribe().fields.getMap(); 
        system.debug(fieldnames[i]);
        List<Schema.PicklistEntry> picklistValues = field_map.get(fieldnames[i]).getDescribe().getPickListValues();
        
        if(nullRequired == true){
            optionlist.add('--None--');
        }
        
        for (Schema.PicklistEntry pv : picklistValues) {
            optionlist.add(pv.getValue());
        }
        picklists.add(optionlist);
        }
        return picklists;
    }
  @Auraenabled
  public static void SaveHSrecord(lead leadObj)
  {
     system.debug('hello');
     Hubspotcreationcalls.createHsformdata(leadobj);
  }
}