unpackaged/main/default/objects/Marketing_Community__c/Marketing_Community__c.object-meta.xml
<CustomObject>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Marketing_Community__c/fields/Assigned_Queue__c.field-meta.xml
<CustomField>
        <fullName>Assigned_Queue__c</fullName>
        <label>Assigned Queue</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Toronto_Pathways</fullName>
                </value>
                <value>
                    <fullName>Toronto_Pinehurst</fullName>
                </value>
                <value>
                    <fullName>Toronto_Woodhaven</fullName>
                </value>
                <value>
                    <fullName>DC_Avendale</fullName>
                </value>
                <value>
                    <fullName>DC_Admirals_Square</fullName>
                </value>
                <value>
                    <fullName>DC_Bradford_s_Landing</fullName>
                </value>
                <value>
                    <fullName>DC_Easton_Village</fullName>
                </value>
                <value>
                    <fullName>DC_Heritage_Shores</fullName>
                </value>
                <value>
                    <fullName>DC_Liberty</fullName>
                </value>
                <value>
                    <fullName>DC_Mayfair</fullName>
                </value>
                <value>
                    <fullName>DC_Oakview_Village</fullName>
                </value>
                <value>
                    <fullName>DC_Potomac_Shores</fullName>
                </value>
                <value>
                    <fullName>DC_Ridgeview</fullName>
                </value>
                <value>
                    <fullName>DC_Bluffs_at_Sleeter_Lake</fullName>
                </value>
                <value>
                    <fullName>DC_Snowden_Bridge_Single_Family</fullName>
                </value>
                <value>
                    <fullName>DC_Snowden_Bridge_Townhomes</fullName>
                </value>
                <value>
                    <fullName>DC_Travilah_Station</fullName>
                </value>
                <value>
                    <fullName>DC_Waterford_Manor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Marketing_Community__c/fields/Sales_office__c.field-meta.xml
<CustomField>
        <fullName>Sales_office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Marketing Communities</relationshipLabel>
        <relationshipName>Marketing_Communities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Sales_Office__c/Sales_Office__c.object-meta.xml
<CustomObject>
    <description>NEWSTAR Sales Office</description>
    <label>Sales Office</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subdivision__c/Subdivision__c.object-meta.xml
<CustomObject>
    <description>NEWSTAR Sales Subdivision</description>
    <label>Subdivision</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subdivisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subdivision__c/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/CachedCollections.cls
public with sharing class CachedCollections {

    private static boolean run = true;
    public static boolean runOnce(){
    System.debug('run variable: ' + run);
        if(run){
            run=false;
            return true;
        }else{
            return run;
        }
    }

    public static List <Marketing_Community__c> myCommunityList {
        get {
            if(myCommunityList == null){
                myCommunityList = [SELECT Name, Id,Assigned_Queue__c,sales_office__c From Marketing_Community__c];
            }
        return myCommunityList;
        }
    set;
    }
    
    public static Map<String, Marketing_Community__c> myCommunityMap {
        get {
            if(myCommunityMap == null){
                myCommunityMap = new Map<String, Marketing_Community__c>();
                for(Marketing_Community__c comm: myCommunityList) {
                    myCommunityMap.put(comm.Name, comm);
                }
            }
            return myCommunityMap;
        }
        set;
    }
    public static List <subdivision__c> mysubdivisionList {
        get {
            if(mysubdivisionlist == null){
                mysubdivisionlist= [SELECT Name, Id From subdivision__c];
            }
        return mysubdivisionlist;
        }
    set;
    }
    
    public static Map<String, subdivision__c> mysubdivisionMap {
        get {
            if(mysubdivisionMap == null){
                mysubdivisionMap = new Map<String, subdivision__c>();
                for(subdivision__c sub: mysubdivisionlist ) {
                    mysubdivisionMap.put(sub.Name, sub);
                }
            }
            return mysubdivisionMap;
        }
        set;
    }
     public static Map<Id,String> mysubdivisionIdMap {
        get {
            if(mysubdivisionIdMap == null){
                mysubdivisionIdMap = new Map<Id,String>();
                for(subdivision__c sub: mysubdivisionList) {
                    mysubdivisionIdMap.put(sub.Id,sub.Name);
                }
            }
            return mysubdivisionIdMap ;
        }
        set;
    }
     public static Map<Id,String> myCommunityIdMap {
        get {
            if(myCommunityIdMap == null){
                myCommunityIdMap = new Map<Id,String>();
                for(Marketing_Community__c comm: myCommunityList) {
                    myCommunityIdMap.put(comm.Id,comm.Name);
                }
            }
            return myCommunityIdMap;
        }
        set;
    }
     public static Map<Id,String> mySalesOfficeIdMap {
        get {
            if(mySalesOfficeIdMap == null){
                mySalesOfficeIdMap = new Map<Id,String>();
                for(Sales_office__c soff: mySalesofficeList ) {
                    mySalesOfficeIdMap.put(soff.Id,soff.Name);
                }
            }
            return mySalesOfficeIdMap ;
        }
        set;
    }
    public static List <Sales_office__c> mySalesofficeList {
        get {
            if(mySalesofficeList == null){
                mySalesofficeList = [SELECT Name, Id From Sales_office__c];
            }
        return mySalesofficeList ;
        }
    set;
    }
     public static Map<String, Sales_office__c> mySalesofficeMap {
        get {
            if(mySalesofficeMap == null){
                mySalesofficeMap = new Map<String, Sales_office__c>();
                for(Sales_office__c soff: mySalesofficeList ) {
                    mySalesofficeMap.put(soff.Name, soff);
                }
            }
            return mySalesofficeMap ;
        }
        set;
    }


     public static List <Profile> myProfileList {
        get {
            if(myProfileList == null){
                myProfileList = [SELECT name, Id From Profile];
            }
        return myProfileList;
        }
    set;
    }

    public static Map<String, Profile> myProfileMap {
        get {
            if(myProfileMap == null){
                myProfileMap = new Map<String, Profile>();
                for(Profile prof: myProfileList) {
                    myProfileMap.put(prof.Name, prof);
                }
            }
            return myProfileMap;
        }
        set;
    }

    public static List <UserRole> myUserRoleList {
        get {
            if(myUserRoleList == null){
                myUserRoleList = [SELECT name, Id From UserRole];
            }
        return myUserRoleList;
        }
    set;
    }

    public static Map<String, UserRole> myUserRoleMap {
        get {
            if(myUserRoleMap == null){
                myUserRoleMap = new Map<String, UserRole>();
                for(UserRole role: myUserRoleList) {
                    myUserRoleMap.put(role.Name, role);
                }
            }
            return myUserRoleMap;
        }
        set;
    }
     public static Map<Id, string> UserRoleMap {
        get {
            if(UserRoleMap == null){
                UserRoleMap = new Map<Id, string>();
                for(UserRole role: myUserRoleList) {
                    UserRoleMap.put(role.Id, role.Name);
                }
            }
            return UserRoleMap;
        }
        set;
    }  
     public static Map<Id, Id> BRPUserRoleMap 
     {
        get {
            if(BRPUserRoleMap == null)
            {
                BRPUserRoleMap = new Map<Id, Id>();
                for(User usr: [Select Id, UserRole.Id from User])
                {
                    BRPUserRoleMap.put(usr.Id, usr.Userrole.Id);
                }

            }
            return BRPUserRoleMap;
        }
         set;
     }
    
    
}