unpackaged/main/default/objects/Contigency__c/Contigency__c.object-meta.xml
<CustomObject>
    <label>Contingency</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contingencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contigency__c/fields/Expiry_date__c.field-meta.xml
<CustomField>
        <fullName>Expiry_date__c</fullName>
        <label>Expiry date</label>
        <required>true</required>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Contigency__c/fields/Met_date__c.field-meta.xml
<CustomField>
        <fullName>Met_date__c</fullName>
        <label>Met date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Contigency__c/fields/Newstar_ID__c.field-meta.xml
<CustomField>
        <fullName>Newstar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Newstar ID</label>
        <length>25</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Contigency__c/fields/Notes__c.field-meta.xml
<CustomField>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </CustomField>

unpackaged/main/default/objects/Contigency__c/fields/Type__c.field-meta.xml
<CustomField>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Home to Sell</fullName>
                </value>
                <value>
                    <fullName>Home to Lease</fullName>
                </value>
                <value>
                    <fullName>Home to Close</fullName>
                </value>
                <value>
                    <fullName>Financing Contingency</fullName>
                </value>
                <value>
                    <fullName>Lawyer Approval</fullName>
                </value>
                <value>
                    <fullName>SiteUnseen Contingency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/classes/NewstarContingencyService.cls
public with sharing class NewstarContingencyService {

    public static void setContingency(Contigency__c con, NewstarContingencyInfo contingencyInfo) {

        con.Newstar_ID__c = contingencyInfo.ContingencyExternalId;          

        con.Type__c = contingencyInfo.Type;

        if (contingencyInfo.ExpiryDate != null)
            con.Expiry_date__c = contingencyInfo.ExpiryDate;

        con.Met_date__c = contingencyInfo.MetDate;
        
        con.Notes__c = contingencyInfo.Notes;
     } 

}