unpackaged/main/default/objects/Newstar_Log_Event__e/Newstar_Log_Event__e.object-meta.xml
<CustomObject>
    <label>NEWSTAR Log Event</label>
    <pluralLabel>NEWSTAR Log Events</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Newstar_Log_Event__e/fields/Context__c.field-meta.xml
<CustomField>
        <fullName>Context__c</fullName>
        <label>Context</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Newstar_Log_Event__e/fields/Correlation_ID__c.field-meta.xml
<CustomField>
        <fullName>Correlation_ID__c</fullName>
        <label>Correlation ID</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Newstar_Log_Event__e/fields/Primary_Object_ID__c.field-meta.xml
<CustomField>
        <fullName>Primary_Object_ID__c</fullName>
        <label>Primary Object ID</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Newstar_Log_Event__e/fields/Status__c.field-meta.xml
<CustomField>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Newstar_Log_Event__e/fields/Trace_Info__c.field-meta.xml
<CustomField>
        <fullName>Trace_Info__c</fullName>
        <label>Trace Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </CustomField>

unpackaged/main/default/objects/Newstar_Log_Event__e/fields/Type__c.field-meta.xml
<CustomField>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Newstar_Log_Record__c/Newstar_Log_Record__c.object-meta.xml
<CustomObject>
    <label>NEWSTAR Log Record</label>
    <nameField>
        <displayFormat>LG{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NEWSTAR Log Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Newstar_Log_Record__c/fields/Correlation_ID__c.field-meta.xml
<CustomField>
        <fullName>Correlation_ID__c</fullName>
        <label>Correlation ID</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Newstar_Log_Record__c/fields/Event_Context__c.field-meta.xml
<CustomField>
        <fullName>Event_Context__c</fullName>
        <label>Event Context</label>
        <length>80</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Newstar_Log_Record__c/fields/Event_Date__c.field-meta.xml
<CustomField>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>DateTime</type>
    </CustomField>

unpackaged/main/default/objects/Newstar_Log_Record__c/fields/Event_Type__c.field-meta.xml
<CustomField>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Newstar_Log_Record__c/fields/Primary_Object_ID__c.field-meta.xml
<CustomField>
        <fullName>Primary_Object_ID__c</fullName>
        <label>Primary Object ID</label>
        <length>20</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Newstar_Log_Record__c/fields/Status__c.field-meta.xml
<CustomField>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                    <default>true</default>
                    <label>Info</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Newstar_Log_Record__c/fields/Trace_Info__c.field-meta.xml
<CustomField>
        <fullName>Trace_Info__c</fullName>
        <label>Trace Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </CustomField>

unpackaged/main/default/classes/NewstarLogEventSubscriberTriggerHandler.cls
public class NewstarLogEventSubscriberTriggerHandler {
    

    public static void processEvents(List<Newstar_Log_Event__e> logEvents) {

        List<Newstar_Log_Record__c> logRecords=new List<Newstar_Log_Record__c>();

        for(Newstar_Log_Event__e logEvent: logEvents) {

            Newstar_Log_Record__c logRecord=new Newstar_Log_Record__c();

            logRecord.Event_Type__c=logEvent.Type__c;
            logRecord.Event_Context__c=logEvent.Context__c;
            logRecord.Primary_Object_ID__c=logEvent.Primary_Object_ID__c;
            logRecord.Trace_Info__c=logEvent.Trace_Info__c;
            logRecord.Correlation_ID__c=logEvent.Correlation_ID__c;
            logRecord.Status__c=logEvent.Status__c;
            logRecord.Event_Date__c=logEvent.CreatedDate;

            logRecords.add(logRecord);
        
        }

        Database.insert(logRecords);
    }

}