unpackaged/main/default/objects/Interest_List__c/Interest_List__c.object-meta.xml
<CustomObject>
    <label>Interest List</label>
    <nameField>
        <label>Interest List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Interest_List__c/fields/Lead__c.field-meta.xml
<CustomField>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Lead_source__c.field-meta.xml
<CustomField>
        <fullName>Lead_source__c</fullName>
        <label>Lead source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advertisement</fullName>
                </value>
                <value>
                    <fullName>Austin Relocation Guide</fullName>
                </value>
                <value>
                    <fullName>BDX</fullName>
                </value>
                <value>
                    <fullName>Billboard</fullName>
                </value>
                <value>
                    <fullName>Brookfield Website</fullName>
                </value>
                <value>
                    <fullName>Builder Boost</fullName>
                </value>
                <value>
                    <fullName>Customer Event</fullName>
                </value>
                <value>
                    <fullName>Direct Mail</fullName>
                </value>
                <value>
                    <fullName>Driving By</fullName>
                </value>
                <value>
                    <fullName>Employee Referral</fullName>
                </value>
                <value>
                    <fullName>External Referral</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Facebook Lead Ad</fullName>
                </value>
                <value>
                    <fullName>Hot On Homes</fullName>
                </value>
                <value>
                    <fullName>Interactive Sales Tool</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Landing Page</fullName>
                </value>
                <value>
                    <fullName>Lightbox</fullName>
                </value>
                <value>
                    <fullName>Live Chat</fullName>
                </value>
                <value>
                    <fullName>Master Plan/Community</fullName>
                </value>
                <value>
                    <fullName>Newspaper/Magazine</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Paid Search</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Partner Referral</fullName>
                </value>
                <value>
                    <fullName>PCR</fullName>
                </value>
                <value>
                    <fullName>Phone Inquiry</fullName>
                </value>
                <value>
                    <fullName>Radio</fullName>
                </value>
                <value>
                    <fullName>Walk-in</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Stage__c.field-meta.xml
<CustomField>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Lead Lost</fullName>
                </value>
                <value>
                    <fullName>Triage for Marketing</fullName>
                    <isActive>false</isActive>
                    <label>Triage for Marketing</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <isActive>false</isActive>
                    <label>Unqualified</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Interest_List__c/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Interest List</relationshipLabel>
        <relationshipName>Interest_List</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Marketing_Community__c/Marketing_Community__c.object-meta.xml
<CustomObject>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Marketing_Community__c/fields/Sales_office__c.field-meta.xml
<CustomField>
        <fullName>Sales_office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Marketing Communities</relationshipLabel>
        <relationshipName>Marketing_Communities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Marketing_Community__c/fields/Sales_Process_Type__c.field-meta.xml
<CustomField>
        <fullName>Sales_Process_Type__c</fullName>
        <defaultValue>'Direct offer'</defaultValue>
        <label>Default Sales Process Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct offer</fullName>
                </value>
                <value>
                    <fullName>Lot reservation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subdivision__c.field-meta.xml
<CustomField>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Subdivision must belong to the selected sales office and the selected marketing community.</errorMessage>
            <filterItems>
                <field>Subdivision__c.Sales_Office__c</field>
                <operation>equals</operation>
                <valueField>$Source.Sales_Office__c</valueField>
            </filterItems>
            <filterItems>
                <field>Subdivision__c.Marketing_Community__c</field>
                <operation>equals</operation>
                <valueField>$Source.Marketing_Community__c</valueField>
            </filterItems>
            <infoMessage>Select a subdivision</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/SalesAgentSalesOfficeLink__c/SalesAgentSalesOfficeLink__c.object-meta.xml
<CustomObject>
    <label>Sales Agent Sales Office Relationship</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agent Sales Office Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAgentSalesOfficeLink__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Sales Agent Sales Office Relationships</relationshipLabel>
        <relationshipName>Sales_Agent_Sales_Office_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/Subdivision__c.object-meta.xml
<CustomObject>
    <description>NEWSTAR Sales Subdivision</description>
    <label>Subdivision</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subdivisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subdivision__c/fields/Marketing_Community__c.field-meta.xml
<CustomField>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Subdivision__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/LeadandinterestListQuickCreateTest.cls
@isTest
private class LeadandinterestListQuickCreateTest
{
    static testmethod void testLeadandInterestListCreate()
    {
        test.startTest();
       
        Sales_Office__c soffice=new Sales_Office__c(Name='Washington Dc');
        insert soffice;
        Marketing_community__c mktcomm=new Marketing_community__c(Name='Avendale', Sales_office__c=soffice.Id,Sales_Process_Type__c='Lot Reservation');
        insert mktcomm;
        Subdivision__c sdiv=new subdivision__c(Name='Avendale 70s', Marketing_Community__c=mktcomm.Id,sales_office__c=soffice.Id);
        insert sdiv;
        Lead ld=new Lead(FirstName='Test1',LastName='Lead Tester', Email='test1@rediff.com');
        Interest_List__c intlst=new Interest_List__c(sales_office__c=soffice.Id,marketing_community__c=mktcomm.Id,subdivision__c=sdiv.Id,Lead_source__c='Facebook');
        string objid=quickLeadcreate.Save(ld,intlst,null,null,null);
        test.stopTest();
        list<Interest_list__c> lstintlst=[select id from Interest_list__c where lead__c =:objid];
        system.assertEquals(1,lstintlst.size());
        
    }
    static testmethod void testDuplicateLead()
    {
        testLeadandInterestListCreate();
        //test.startTest();
        Lead ld=new Lead(FirstName='Test1',LastName='Lead Tester', Email='test1@rediff.com');
        AccountandLead aclead=new AccountandLead();
        aclead=quickLeadcreate.AccountAndLeadRecords(ld);
       // test.stopTest();
        system.assertEquals(0,aclead.a.size());
        system.assertEquals(1,aclead.c.size());
        
    }
    static testmethod void testDuplicateAccount()
    {
        testAccountcreate();
        //test.startTest();
        Lead ld=new Lead(FirstName='Test1',LastName='Lead Tester', Email='test1@rediff.com');
        AccountandLead aclead=new AccountandLead();
        aclead=quickLeadcreate.AccountAndLeadRecords(ld);
       // test.stopTest();
        system.assertEquals(1,aclead.a.size());
        system.assertEquals(0,aclead.c.size());
        
    }
    static testmethod void testAccountcreate()
    {
        test.startTest();
        String RecTypeId= [select Id from RecordType where (Name='Person Account') and (SobjectType='Account')].Id;
        Account acc=new Account( RecordTypeID=RecTypeId,FirstName='Test1',LastName='Lead Tester', PersonEmail='test1@rediff.com');
        insert acc;
        test.stopTest();
    }
    static testmethod void testDuplicateInterestList()
    {
        test.startTest();
        Lead ld=new Lead(FirstName='Test1',LastName='Lead Tester', Email='test1@rediff.com');
        insert ld;
        Sales_Office__c soffice=new Sales_Office__c(Name='Washington Dc');
        insert soffice;
        Marketing_community__c mktcomm=new Marketing_community__c(Name='Avendale', Sales_office__c=soffice.Id,Sales_Process_Type__c='Lot Reservation');
        insert mktcomm;
        Subdivision__c sdiv=new subdivision__c(Name='Avendale 70s', Marketing_Community__c=mktcomm.Id,sales_office__c=soffice.Id);
        insert sdiv;
        Interest_List__c intlst1=new Interest_List__c(lead__c=ld.Id,sales_office__c=soffice.Id,marketing_community__c=mktcomm.Id,subdivision__c=sdiv.Id,Lead_source__c='Facebook',Stage__c='Working',Interest_status__c='Responded Nurture');
        insert intlst1;
        Interest_List__c intlst2=new Interest_List__c(lead__c=ld.Id,sales_office__c=soffice.Id,marketing_community__c=mktcomm.Id,subdivision__c=sdiv.Id,Lead_source__c='Facebook',Stage__c='Working',Interest_status__c='Responded Nurture');
        quickLeadcreate.Save(ld,intlst2,null,ld.Id,null);
        test.stopTest();
        list<Interest_list__c> lstintlst=[select id from Interest_list__c where lead__c =:ld.Id];
        system.assertEquals(1,lstintlst.size());
        list<beback__c> beback=[select id from beback__c where Community_of_Interest__c =:intlst1.Id];
        system.assertEquals(1,beback.size());
        
    }
    static testmethod void testNotDuplicateInterestList()
    {
        test.startTest();
        Lead ld=new Lead(FirstName='Test1',LastName='Lead Tester', Email='test1@rediff.com');
        insert ld;
        Sales_Office__c soffice=new Sales_Office__c(Name='Washington Dc');
        insert soffice;
        Marketing_community__c mktcomm=new Marketing_community__c(Name='Avendale', Sales_office__c=soffice.Id,Sales_Process_Type__c='Lot Reservation');
        insert mktcomm;
        Subdivision__c sdiv=new subdivision__c(Name='Avendale 70s', Marketing_Community__c=mktcomm.Id,sales_office__c=soffice.Id);
        insert sdiv;
        Interest_List__c intlst1=new Interest_List__c(lead__c=ld.Id,sales_office__c=soffice.Id,marketing_community__c=mktcomm.Id,subdivision__c=sdiv.Id,Lead_source__c='Facebook',Stage__c='Lead Lost');
        insert intlst1;
        Interest_List__c intlst2=new Interest_List__c(lead__c=ld.Id,sales_office__c=soffice.Id,marketing_community__c=mktcomm.Id,subdivision__c=sdiv.Id,Lead_source__c='Facebook',Stage__c='Working',Interest_status__c='Responded Nurture');
        quickLeadcreate.Save(ld,intlst2,null,ld.Id,null);
        test.stopTest();
        list<Interest_list__c> lstintlst=[select id from Interest_list__c where lead__c =:ld.Id];
        system.assertEquals(2,lstintlst.size());
        list<beback__c> beback=[select id from beback__c where Community_of_Interest__c =:intlst1.Id];
        system.assertEquals(0,beback.size());
        
    }
    static testmethod void testDuplicateAccountWithNewOpportunity()
    {
        test.startTest();
        String RecTypeId= [select Id from RecordType where (Name='Person Account') and (SobjectType='Account')].Id;
        Account acc=new Account( RecordTypeID=RecTypeId,FirstName='Test1',LastName='Lead Tester', PersonEmail='test1@rediff.com');
        insert acc;
        Lead ld=new Lead(FirstName='Test1',LastName='Lead Tester', Email='test1@rediff.com');
        Sales_Office__c soffice=new Sales_Office__c(Name='Washington Dc');
        insert soffice;
        Marketing_community__c mktcomm=new Marketing_community__c(Name='Avendale', Sales_office__c=soffice.Id,Sales_Process_Type__c='Lot Reservation');
        insert mktcomm;
        Subdivision__c sdiv=new subdivision__c(Name='Avendale 70s', Marketing_Community__c=mktcomm.Id,sales_office__c=soffice.Id);
        insert sdiv;
        Interest_List__c intlst1=new Interest_List__c(lead__c=ld.Id,sales_office__c=soffice.Id,marketing_community__c=mktcomm.Id,subdivision__c=sdiv.Id,Lead_source__c='Facebook',Stage__c='Working',Interest_status__c='Responded Nurture');
        quickLeadcreate.Save(ld,intlst1,null,null,acc.Id);
        test.stopTest();
        list<Opportunity> lstopp=[select id from opportunity where accountid =:acc.Id];
        system.assertEquals(1,lstopp.size());
    }
    static testmethod void Subdivisions()
    {
        Sales_Office__c soffice=new Sales_Office__c(Name='Washington Dc');
        insert soffice;
        Marketing_community__c mktcomm=new Marketing_community__c(Name='Avendale', Sales_office__c=soffice.Id,Sales_Process_Type__c='Lot Reservation');
        insert mktcomm;
        Subdivision__c sdiv=new subdivision__c(Name='Avendale 70s', Marketing_Community__c=mktcomm.Id,sales_office__c=soffice.Id);
        insert sdiv;
        list<subdivision__c> lstsubdiv=quickLeadcreate.getSubdivisions(mktcomm.Id,soffice.Id);
        system.assertEquals(1,lstsubdiv.size());
    }
    static testmethod void Marketingcommunity()
    {
        Sales_Office__c soffice=new Sales_Office__c(Name='Washington Dc');
        insert soffice;
        Marketing_community__c mktcomm=new Marketing_community__c(Name='Avendale', Sales_office__c=soffice.Id,Sales_Process_Type__c='Lot Reservation');
        insert mktcomm;
        list<Marketing_community__c> lstmktcomm=quickLeadcreate.getMktcommunity(soffice.Id);
        system.assertEquals(1,lstmktcomm.size());
    }
    static testmethod void SalesOffice()
    {
        Sales_Office__c soffice=new Sales_Office__c(Name='Washington Dc');
        insert soffice;
        sales_agent__c sagent=new Sales_agent__c(first_name__c='Test',last_name__c='User1', related_to_user__c=userinfo.getUserId());
        insert sagent;
        SalesAgentSalesOfficeLink__c  sofficelink=new SalesAgentSalesOfficeLink__c (sales_agent__c=sagent.Id,sales_office__c=soffice.Id);
        insert sofficelink;
        list<SalesAgentSalesOfficeLink__c> lstsaleslink=quickLeadcreate.getSalesOffices();
        system.assertEquals(1,lstsaleslink.size());

    }
    static testmethod void testLeadconversion()
    {
        test.startTest();
        Lead ld=new Lead(FirstName='Test1',LastName='Lead Tester', Email='test1@rediff.com');
        insert ld;
        Sales_Office__c soffice=new Sales_Office__c(Name='Washington Dc');
        insert soffice;
        Marketing_community__c mktcomm1=new Marketing_community__c(Name='Avendale', Sales_office__c=soffice.Id,Sales_Process_Type__c='Lot Reservation');
        insert mktcomm1;
        Subdivision__c sdiv=new subdivision__c(Name='Avendale 70s', Marketing_Community__c=mktcomm1.Id,sales_office__c=soffice.Id);
        insert sdiv;
        Marketing_community__c mktcomm2=new Marketing_community__c(Name='Oakdale Projects', Sales_office__c=soffice.Id,Sales_Process_Type__c='Direct Offer');
        insert mktcomm2;
        Interest_List__c intlst1=new Interest_List__c(lead__c=ld.Id,sales_office__c=soffice.Id,marketing_community__c=mktcomm1.Id,subdivision__c=sdiv.Id,Lead_source__c='Walk-in',Stage__c='Working',Interest_status__c='Responded Nurture');
        insert intlst1;
        Interest_List__c intlst2=new Interest_List__c(lead__c=ld.Id,sales_office__c=soffice.Id,marketing_community__c=mktcomm2.Id,subdivision__c=sdiv.Id,Lead_source__c='Facebook',Stage__c='Working',Interest_status__c='Responded Nurture');
        insert intlst2;
        test.stopTest();
        list<Interest_list__c> lstintlst=quickLeadcreate.getInterestLists(ld.Id);
        system.assertEquals(2,lstintlst.size());
        Id accId=LeadConvertController.leadconvert(ld.Id);
        list<Opportunity> lstopp=quickLeadcreate.getOpportunities(accId);
        system.assertEquals(2,lstopp.size());
        list<lead> lstlead=[select id from lead where id=:ld.Id and isconverted=true];
        system.assertEquals(1,lstlead.size());
        
    }
    
}